### ISSUE TITLE
Ingen data siden igår aftes kl 23:08

### ISSUE THREAD

**Issue by ghozt1989** [scaarup/aula#155]
Hej ved ikke om det kun er hos mig der ingen data har været siden kl 23:08 igår aftes? :)

**Comment by scaarup** [comment]
Hej.
Det virker fint her.
Jeg ved ikke hvordan du tænker jeg skal fejlsøge ? Ingen logs eller noget info.

Men inden du begynder at grave det frem, så check lige debug loggen selv og verificér, at dit unilogin password ikke er udløbet. Tror det sker hver 3. måned.

**Comment by ghozt1989** [comment]
Beklager min fejl søren. Du får lige hvad jeg har kunne finde frem her

![image](https://github.com/scaarup/aula/assets/7705364/cc69ebe6-3071-4982-b356-160c871e0806)
![image](https://github.com/scaarup/aula/assets/7705364/b61c2b45-2fdb-4ba6-bd9c-3ed679f26df1)
![image](https://github.com/scaarup/aula/assets/7705364/ffd0b170-c915-4df5-8a3e-171078e6dcec)

**Comment by scaarup** [comment]
Har du gjort hvad der står i loglinjen og som jeg skrev i går?

**Comment by ghozt1989** [comment]
Det med at skifte koden gjorde jeg som det aller første da jeg før har haft det problem så den er udelukket :(

**Comment by scaarup** [comment]
okay og efter du skiftede password, slettede du aula integrationen og satte den op på ny med det nye password?

**Comment by sanded001** [comment]
Får også fejl på aula. Unilogin virker fint andre steder, så formentlig deres api som sejler. har downgradet aula til 1.36 men får forsat ingen data. 

Min gik ned igår kl 22.08.

Aula 1.36 log version. 
____________________________________

Unexpected error fetching sensor data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 271, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/aula/sensor.py", line 60, in async_update_data
    await hass.async_add_executor_job(client.update_data)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/aula/client.py", line 225, in update_data
    self.login()
  File "/config/custom_components/aula/client.py", line 125, in login
    url = html.form["action"]
          ~~~~~~~~~^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by nickknissen** [comment]
@sanded001 Prøv lige at tjekke om dit unilogin virker til aula. Jeg får nemlig beskeden `Dit login giver ikke adgang til Aula` og mit login har virket tidligere.

Så jeg tror det er i forbindelse med at Aula har problemer med login. 
>	Login
Der opleves i øjeblikket udfordringer at forældre/kontaktpersoner ikke kan logge på aula.dk og i Aula app.
Der arbejdes på at løse problemet.
https://aulainfo.dk/driftstatus/

**Comment by sanded001** [comment]
> @sanded001 Prøv lige at tjekke om dit unilogin virker til aula. Jeg får nemlig beskeden `Dit login giver ikke adgang til Aula` og mit login har virket tidligere.
> 
> Så jeg tror det er i forbindelse med at Aula har problemer med login.
> 
> > Login
> > Der opleves i øjeblikket udfordringer at forældre/kontaktpersoner ikke kan logge på aula.dk og i Aula app.
> > Der arbejdes på at løse problemet.
> > https://aulainfo.dk/driftstatus/

Tjek - det er nok der issuet ligger. :) Tak for driftstatus.

**Comment by Oceanfarm** [comment]
Her har det heller ikke virket et par dage. Får følgende fejl i loggen:

Error while setting up aula platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 356, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/aula/sensor.py", line 75, in async_setup_entry
    await hass.async_add_executor_job(client.update_data)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/aula/client.py", line 218, in update_data
    self.apiurl + "?method=profiles.getProfilesByLogin", verify=True
    ^^^^^^^^^^^
AttributeError: 'Client' object has no attribute 'apiurl'

**Comment by nickknissen** [comment]
@Oceanfarm Prøv at fjern integrationen og så tilføj den igen.

**Comment by sanded001** [comment]
> Her har det heller ikke virket et par dage. Får følgende fejl i loggen:
> 
> Error while setting up aula platform for sensor Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 356, in _async_setup_platform await asyncio.shield(awaitable) File "/config/custom_components/aula/sensor.py", line 75, in async_setup_entry await hass.async_add_executor_job(client.update_data) File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/config/custom_components/aula/client.py", line 218, in update_data self.apiurl + "?method=profiles.getProfilesByLogin", verify=True ^^^^^^^^^^^ AttributeError: 'Client' object has no attribute 'apiurl'

Mit virker igen efter Aula har fået fingeren ud :) - prøv lige at slette og reconnecte i HA

**Comment by Oceanfarm** [comment]
> @Oceanfarm Prøv at fjern integrationen og så tilføj den igen.

Tjek! Virker igen. :)

**Comment by ghozt1989** [comment]
Hej i skal slette aula helt også total genstarte jeres HA også smide aula ind igen så skulle det virke ☺️

**Comment by scaarup** [comment]
Er der stadig problemer her?

**Comment by victordk** [comment]
Unexpected error fetching sensor data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 271, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/aula/sensor.py", line 60, in async_update_data
    await hass.async_add_executor_job(client.update_data)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/aula/client.py", line 373, in update_data
    self.get_widgets()
  File "/config/custom_components/aula/client.py", line 183, in get_widgets
    detected_widgets = self._session.get(
                       ^^^^^^^^^^^^^^^^^^
KeyError: 'moduleWidgetConfiguration'

Kæmper lidt med ovenstående til aften - har slettet Aula - genstartet - ændret password osv.

**Comment by scaarup** [comment]
Har du set der er en ny beta/pre release ?

**Comment by victordk** [comment]
> Har du set der er en ny beta/pre release ?

Tak det virkede! - dog uden ugeplanen men det har ikke virket i flere måneder  :)
