### ISSUE TITLE
Udfald i Aula integration: TypeError ved opdatering af ugeplan

### ISSUE THREAD

**Issue by Jogge** [scaarup/aula#177]
**Describe the bug or problem (In Danish is OK)**

![Aula-integration-udfald](https://github.com/user-attachments/assets/c5e6dd1b-eb43-49a8-9e4a-895f7bbbb723)

Jeg har på det seneste oplevet en del udfald i Aula integrationen, som kan ses i grafen herover.

Loggen indeholder fejlen, samt når det går godt både før og efter fejlen.

**Please answer the following**
- Version of integration: 0.1.40
- Version of Home Assistant: 2024.9.0
- [x] I have more than one child
- [x] My children are attending different schools / institutions (En pige i børnehave, og to drenge på samme skole)

Log:

```
2024-09-06 08:55:22.854 DEBUG (SyncWorker_51) [custom_components.aula.client] is_logged_in? True
2024-09-06 08:55:22.854 DEBUG (SyncWorker_51) [custom_components.aula.client] Child ids and names: {1000001: 'Pige M', 1000002: 'Dreng E', 1000003: 'Dreng A'}
2024-09-06 08:55:22.855 DEBUG (SyncWorker_51) [custom_components.aula.client] Child ids and institution names: {1000001: 'Børnehaven', 1000002: 'Skolen', 1000003: 'Skolen'}
2024-09-06 08:55:22.855 DEBUG (SyncWorker_51) [custom_components.aula.client] Institution codes: ['G20001', '600001']
2024-09-06 08:55:23.278 DEBUG (SyncWorker_51) [custom_components.aula.client] Child ids and presence data status: {'1000001': 1, '1000002': 1, '1000003': 1}
2024-09-06 08:55:24.315 DEBUG (SyncWorker_51) [custom_components.aula.client] Fetching calendars...
2024-09-06 08:55:25.197 DEBUG (SyncWorker_51) [custom_components.aula.client] In the Meebook flow...
2024-09-06 08:55:25.198 DEBUG (SyncWorker_51) [custom_components.aula.client] Requesting new token for widget 0004
2024-09-06 08:55:25.494 DEBUG (SyncWorker_51) [custom_components.aula.client] Meebook ugeplan for Dreng E
2024-09-06 08:55:25.494 DEBUG (SyncWorker_51) [custom_components.aula.client] Meebook ugeplan for Dreng A
2024-09-06 08:55:25.497 DEBUG (SyncWorker_51) [custom_components.aula.client] In the Meebook flow...
2024-09-06 08:55:25.497 DEBUG (SyncWorker_51) [custom_components.aula.client] Reusing existing token for widget 0004
2024-09-06 08:55:25.661 DEBUG (SyncWorker_51) [custom_components.aula.client] Meebook ugeplan for Dreng E
2024-09-06 08:55:25.661 DEBUG (SyncWorker_51) [custom_components.aula.client] Meebook ugeplan for Dreng A
2024-09-06 08:55:25.666 DEBUG (MainThread) [custom_components.aula.sensor] Finished fetching sensor data in 3.101 seconds (success: True)
2024-09-06 08:55:25.667 DEBUG (MainThread) [custom_components.aula.sensor] Could not get ugeplan for next week for child Pige M. Perhaps not available yet.
2024-09-06 08:55:27.668 DEBUG (SyncWorker_3) [custom_components.aula.binary_sensor] There are unread message(s)

2024-09-06 08:59:29.712 DEBUG (SyncWorker_63) [custom_components.aula.calendar] Updating calendars...
2024-09-06 08:59:29.733 DEBUG (SyncWorker_63) [custom_components.aula.calendar] Parsing skoleskema.json...
2024-09-06 08:59:29.758 DEBUG (SyncWorker_37) [custom_components.aula.calendar] Updating calendars...
2024-09-06 08:59:29.768 DEBUG (SyncWorker_37) [custom_components.aula.calendar] Parsing skoleskema.json...

2024-09-06 09:00:25.972 DEBUG (SyncWorker_50) [custom_components.aula.client] is_logged_in? True
2024-09-06 09:00:25.972 DEBUG (SyncWorker_50) [custom_components.aula.client] Child ids and names: {1000001: 'Pige M', 1000002: 'Dreng E', 1000003: 'Dreng A'}
2024-09-06 09:00:25.973 DEBUG (SyncWorker_50) [custom_components.aula.client] Child ids and institution names: {1000001: 'Børnehaven', 1000002: 'Skolen', 1000003: 'Skolen'}
2024-09-06 09:00:25.973 DEBUG (SyncWorker_50) [custom_components.aula.client] Institution codes: ['G20001', '600001']
2024-09-06 09:00:26.526 DEBUG (SyncWorker_50) [custom_components.aula.client] Child ids and presence data status: {'1000001': 1, '1000002': 1, '1000003': 1}
2024-09-06 09:00:27.669 DEBUG (SyncWorker_6) [custom_components.aula.binary_sensor] There are unread message(s)
2024-09-06 09:00:28.031 DEBUG (SyncWorker_50) [custom_components.aula.client] Fetching calendars...
2024-09-06 09:00:28.824 DEBUG (SyncWorker_50) [custom_components.aula.client] In the Meebook flow...
2024-09-06 09:00:28.824 DEBUG (SyncWorker_50) [custom_components.aula.client] Requesting new token for widget 0004
2024-09-06 09:00:29.084 ERROR (MainThread) [custom_components.aula.sensor] Unexpected error fetching sensor data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 271, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/aula/sensor.py", line 60, in async_update_data
    await hass.async_add_executor_job(client.update_data)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/aula/client.py", line 759, in update_data
    ugeplan(thisweek, "this")
  File "/config/custom_components/aula/client.py", line 731, in ugeplan
    _LOGGER.debug("Meebook ugeplan for " + person["name"])
                                           ~~~~~~^^^^^^^^
TypeError: string indices must be integers, not 'str'
2024-09-06 09:00:29.093 DEBUG (MainThread) [custom_components.aula.sensor] Finished fetching sensor data in 3.528 seconds (success: False)

2024-09-06 09:03:29.713 DEBUG (SyncWorker_2) [custom_components.aula.calendar] Updating calendars...
2024-09-06 09:03:29.730 DEBUG (SyncWorker_2) [custom_components.aula.calendar] Parsing skoleskema.json...

2024-09-06 09:05:27.670 DEBUG (SyncWorker_33) [custom_components.aula.binary_sensor] There are unread message(s)
2024-09-06 09:05:28.904 DEBUG (SyncWorker_3) [custom_components.aula.client] is_logged_in? True
2024-09-06 09:05:28.905 DEBUG (SyncWorker_3) [custom_components.aula.client] Child ids and names: {1000001: 'Pige M', 1000002: 'Dreng E', 1000003: 'Dreng A'}
2024-09-06 09:05:28.905 DEBUG (SyncWorker_3) [custom_components.aula.client] Child ids and institution names: {1000001: 'Børnehaven', 1000002: 'Skolen', 1000003: 'Skolen'}
2024-09-06 09:05:28.905 DEBUG (SyncWorker_3) [custom_components.aula.client] Institution codes: ['G20001', '600001']
2024-09-06 09:05:29.401 DEBUG (SyncWorker_3) [custom_components.aula.client] Child ids and presence data status: {'1000001': 1, '1000002': 1, '1000003': 1}
2024-09-06 09:05:31.206 DEBUG (SyncWorker_3) [custom_components.aula.client] Fetching calendars...
2024-09-06 09:05:32.009 DEBUG (SyncWorker_3) [custom_components.aula.client] In the Meebook flow...
2024-09-06 09:05:32.009 DEBUG (SyncWorker_3) [custom_components.aula.client] Requesting new token for widget 0004
2024-09-06 09:05:32.367 DEBUG (SyncWorker_3) [custom_components.aula.client] Meebook ugeplan for Dreng E
2024-09-06 09:05:32.368 DEBUG (SyncWorker_3) [custom_components.aula.client] Meebook ugeplan for Dreng A
2024-09-06 09:05:32.369 DEBUG (SyncWorker_3) [custom_components.aula.client] In the Meebook flow...
2024-09-06 09:05:32.369 DEBUG (SyncWorker_3) [custom_components.aula.client] Reusing existing token for widget 0004
2024-09-06 09:05:32.550 DEBUG (SyncWorker_3) [custom_components.aula.client] Meebook ugeplan for Dreng E
2024-09-06 09:05:32.550 DEBUG (SyncWorker_3) [custom_components.aula.client] Meebook ugeplan for Dreng A
2024-09-06 09:05:32.553 INFO (MainThread) [custom_components.aula.sensor] Fetching sensor data recovered
2024-09-06 09:05:32.553 DEBUG (MainThread) [custom_components.aula.sensor] Finished fetching sensor data in 3.988 seconds (success: True)
2024-09-06 09:05:32.554 DEBUG (MainThread) [custom_components.aula.sensor] Could not get ugeplan for next week for child Pige M. Perhaps not available yet.
```

**Comment by Jogge** [comment]
Jeg har indsat følgende to linjer:

```python
_LOGGER.debug("Data type: " + str(type(data)))
_LOGGER.debug("Data content: " + str(data))
```

... lige før denne linje:

https://github.com/scaarup/aula/blob/9e729a289dd1d6f65770ab27b1222e8f90ac7bc4/custom_components/aula/client.py#L730

Herefter kan jeg se i loggen, at når det går galt, er det fordi den mener min AULA-token ikke er gyldig:

```
2024-09-11 08:38:17.773 DEBUG (SyncWorker_3) [custom_components.aula.client] Data type: <class 'dict'>
2024-09-11 08:38:17.773 DEBUG (SyncWorker_3) [custom_components.aula.client] Data content: {'supportId': '9896xxxx', 'exceptionMessage': 'Support-ID 9896xxxx - Din AULA-token er ikke gyldig'}
```

Men næste gang den forsøger, så virker min AULA-token fint.

**Comment by Jogge** [comment]
Fixed in https://github.com/scaarup/aula/pull/178
