### ISSUE TITLE
Error while setting up aula platform for sensor

### ISSUE THREAD

**Issue by thomaspalmdk** [scaarup/aula#19]
Med høje forventninger installerede jeg denne integration :-)
Har genstartet HA et par gange, men i min log har jeg et par fejl - måske er de uden betydning?
Anyways; jeg laver lige et issue på hver af fejlene.

Snip direkte fra HA-loggen:

```
Logger: homeassistant.components.sensor
Source: custom_components/aula/client.py:113
Integration: Sensor (documentation, issues)
First occurred: 20.02.14 (1 occurrences)
Last logged: 20.02.14

Error while setting up aula platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/aula/sensor.py", line 55, in async_setup_entry
    await hass.async_add_executor_job(client.update_data)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/aula/client.py", line 122, in update_data
    ugeplan(thisweek,"this")
  File "/config/custom_components/aula/client.py", line 113, in ugeplan
    for person in ugeplaner.json()["personer"]:
KeyError: 'personer'

```

**Comment by scaarup** [comment]
Det her lader til at være en dup af issue #17
