### ISSUE TITLE
Ugekalender virker ikke

### ISSUE THREAD

**Issue by sorenbache** [scaarup/aula#190]
**Describe the bug or problem (In Danish is OK)**

**Please answer the following**
- Version of integration: 0.1.42
- Version of Home Assistant: 2024.10
- [ ] I have more than one child
- [ ] My children are attending different schools / institutions

```
2024-10-29 21:10:49.261 INFO (MainThread) [custom_components.aula] 
                _
     /\        | |
    /  \  _   _| | __ _
   / /\ \| | | | |/ _` |
  / ____ \ |_| | | (_| |
 /_/    \_\__,_|_|\__,_|
Aula integration, version: 0.1.42
This is a custom integration
If you have any issues with this you need to open an issue here:
https://github.com/scaarup/aula/issues
-------------------------------------------------------------------

2024-10-29 21:10:49.320 INFO (MainThread) [homeassistant.components.sensor] Setting up aula.sensor
2024-10-29 21:10:49.322 DEBUG (SyncWorker_20) [custom_components.aula.client] is_logged_in? False
2024-10-29 21:10:49.322 DEBUG (SyncWorker_20) [custom_components.aula.client] Logging in
2024-10-29 21:10:50.969 DEBUG (SyncWorker_20) [custom_components.aula.client] Trying API at https://www.aula.dk/api/v19
2024-10-29 21:10:51.015 DEBUG (SyncWorker_20) [custom_components.aula.client] API was expected at https://www.aula.dk/api/v19 but responded with HTTP 410. The integration will automatically try a newer version and everything may work fine.
2024-10-29 21:10:51.015 DEBUG (SyncWorker_20) [custom_components.aula.client] Trying API at https://www.aula.dk/api/v20
2024-10-29 21:10:51.165 DEBUG (SyncWorker_20) [custom_components.aula.client] Found API on https://www.aula.dk/api/v20
2024-10-29 21:10:51.362 DEBUG (SyncWorker_20) [custom_components.aula.client] LOGIN: True
2024-10-29 21:10:51.362 DEBUG (SyncWorker_20) [custom_components.aula.client] Config - schoolschedule: True, config - ugeplaner: True
2024-10-29 21:10:51.363 DEBUG (SyncWorker_20) [custom_components.aula.client] Child ids and names: {111111111: 'xxxxxxx'}
2024-10-29 21:10:51.363 DEBUG (SyncWorker_20) [custom_components.aula.client] Child ids and institution names: {111111111: 'XXXX Skole'}
2024-10-29 21:10:51.363 DEBUG (SyncWorker_20) [custom_components.aula.client] Institution codes: ['777777']
2024-10-29 21:10:51.448 DEBUG (SyncWorker_20) [custom_components.aula.client] Unable to retrieve presence data from Aula from child with id 111111111. Some data will be missing from sensor entities.
2024-10-29 21:10:51.448 DEBUG (SyncWorker_20) [custom_components.aula.client] Child ids and presence data status: {'111111111': 0}
2024-10-29 21:10:51.982 DEBUG (SyncWorker_20) [custom_components.aula.client] Fetching calendars...
2024-10-29 21:10:52.776 DEBUG (SyncWorker_20) [custom_components.aula.client] In the MU Opgaver flow
2024-10-29 21:10:52.776 DEBUG (SyncWorker_20) [custom_components.aula.client] Requesting new token for widget 0030
2024-10-29 21:10:54.901 DEBUG (SyncWorker_20) [custom_components.aula.client] MU Opgaver status_code 200
2024-10-29 21:10:54.902 DEBUG (SyncWorker_20) [custom_components.aula.client] MU Opgaver response {"opgaver":[]}
2024-10-29 21:10:54.902 DEBUG (SyncWorker_20) [custom_components.aula.client] MU Opgaver result: 
2024-10-29 21:10:54.904 DEBUG (SyncWorker_20) [custom_components.aula.client] In the MU Opgaver flow
2024-10-29 21:10:54.904 DEBUG (SyncWorker_20) [custom_components.aula.client] Reusing existing token for widget 0030
2024-10-29 21:10:54.942 DEBUG (SyncWorker_20) [custom_components.aula.client] MU Opgaver status_code 200
2024-10-29 21:10:54.942 DEBUG (SyncWorker_20) [custom_components.aula.client] MU Opgaver response {"opgaver":[]}
2024-10-29 21:10:54.942 DEBUG (SyncWorker_20) [custom_components.aula.client] MU Opgaver result: 
2024-10-29 21:10:54.949 DEBUG (MainThread) [custom_components.aula.sensor] Finished fetching sensor data in 5.628 seconds (success: True)
2024-10-29 21:10:55.042 DEBUG (SyncWorker_19) [custom_components.aula.client] is_logged_in? True
2024-10-29 21:10:55.042 DEBUG (SyncWorker_19) [custom_components.aula.client] Child ids and names: {111111111: 'xxxxxxx'}
2024-10-29 21:10:55.042 DEBUG (SyncWorker_19) [custom_components.aula.client] Child ids and institution names: {111111111: 'XXXX Skole'}
2024-10-29 21:10:55.042 DEBUG (SyncWorker_19) [custom_components.aula.client] Institution codes: ['777777']
2024-10-29 21:10:55.119 DEBUG (SyncWorker_19) [custom_components.aula.client] Unable to retrieve presence data from Aula from child with id 111111111. Some data will be missing from sensor entities.
2024-10-29 21:10:55.119 DEBUG (SyncWorker_19) [custom_components.aula.client] Child ids and presence data status: {'111111111': 0}
2024-10-29 21:10:55.725 DEBUG (SyncWorker_19) [custom_components.aula.client] Fetching calendars...
2024-10-29 21:10:56.525 DEBUG (SyncWorker_19) [custom_components.aula.client] In the MU Opgaver flow
2024-10-29 21:10:56.526 DEBUG (SyncWorker_19) [custom_components.aula.client] Reusing existing token for widget 0030
2024-10-29 21:10:56.567 DEBUG (SyncWorker_19) [custom_components.aula.client] MU Opgaver status_code 200
2024-10-29 21:10:56.567 DEBUG (SyncWorker_19) [custom_components.aula.client] MU Opgaver response {"opgaver":[]}
2024-10-29 21:10:56.568 DEBUG (SyncWorker_19) [custom_components.aula.client] MU Opgaver result: 
2024-10-29 21:10:56.568 DEBUG (SyncWorker_19) [custom_components.aula.client] In the MU Opgaver flow
2024-10-29 21:10:56.568 DEBUG (SyncWorker_19) [custom_components.aula.client] Reusing existing token for widget 0030
2024-10-29 21:10:56.614 DEBUG (SyncWorker_19) [custom_components.aula.client] MU Opgaver status_code 200
2024-10-29 21:10:56.615 DEBUG (SyncWorker_19) [custom_components.aula.client] MU Opgaver response {"opgaver":[]}
2024-10-29 21:10:56.615 DEBUG (SyncWorker_19) [custom_components.aula.client] MU Opgaver result: 
2024-10-29 21:10:56.642 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Aula for calendar
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 322, in async_setup_entry
    return await hass.data[DATA_COMPONENT].async_setup_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 183, in async_setup_entry
    raise ValueError(
ValueError: Config entry Aula (01JBADW0SSMJ3VA6B7XVN6M8NZ) for aula.calendar has already been setup!
2024-10-29 21:10:56.650 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Aula for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 232, in async_setup_entry
    return await hass.data[DATA_COMPONENT].async_setup_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 183, in async_setup_entry
    raise ValueError(
ValueError: Config entry Aula (01JBADW0SSMJ3VA6B7XVN6M8NZ) for aula.binary_sensor has already been setup!
2024-10-29 21:10:56.651 DEBUG (MainThread) [custom_components.aula.sensor] Unique ID for child 111111111 aula111111111
2024-10-29 21:10:56.651 DEBUG (MainThread) [custom_components.aula.sensor] Unique ID for child 111111111 aula111111111
2024-10-29 21:10:56.651 DEBUG (MainThread) [custom_components.aula.sensor] Unique ID for child 111111111 aula111111111
2024-10-29 21:10:56.652 DEBUG (MainThread) [custom_components.aula.sensor] Setting state to n/a for child 111111111
2024-10-29 21:10:56.656 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that calls async_forward_entry_setup for integration aula with title: Aula and entry_id: 01JBADW0SSMJ3VA6B7XVN6M8NZ, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.
Stack (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2223, in async_forward_entry_setup
    _report_non_awaited_platform_forwards(entry, "async_forward_entry_setup")
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1192, in _report_non_awaited_platform_forwards
    report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 155, in report
    _LOGGER.warning(msg, stack_info=True)
2024-10-29 21:11:05.169 DEBUG (SyncWorker_57) [custom_components.aula.client] is_logged_in? True
2024-10-29 21:11:05.170 DEBUG (SyncWorker_57) [custom_components.aula.client] Child ids and names: {111111111: 'xxxxxxx'}
2024-10-29 21:11:05.170 DEBUG (SyncWorker_57) [custom_components.aula.client] Child ids and institution names: {111111111: 'XXXX Skole'}
2024-10-29 21:11:05.170 DEBUG (SyncWorker_57) [custom_components.aula.client] Institution codes: ['777777']
2024-10-29 21:11:05.322 DEBUG (SyncWorker_57) [custom_components.aula.client] Unable to retrieve presence data from Aula from child with id 111111111. Some data will be missing from sensor entities.
2024-10-29 21:11:05.322 DEBUG (SyncWorker_57) [custom_components.aula.client] Child ids and presence data status: {'111111111': 0}
2024-10-29 21:11:06.176 DEBUG (SyncWorker_57) [custom_components.aula.client] Fetching calendars...
2024-10-29 21:11:07.033 INFO (MainThread) [surepy.client] 🐾 [38;2;255;0;255m·[0m GET app.api.surehub.io/api/report/household/43686: 404 | <ClientResponse(https://app.api.surehub.io/api/report/household/43686) [404 Not Found]>
<CIMultiDictProxy('Date': 'Tue, 29 Oct 2024 20:11:06 GMT', 'Content-Length': '0', 'Connection': 'keep-alive', 'Server': 'nginx', 'Access-Control-Allow-Origin': '*', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains; preload', 'X-Frame-Options': 'DENY', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block')>

2024-10-29 21:11:07.057 DEBUG (SyncWorker_57) [custom_components.aula.client] In the MU Opgaver flow
2024-10-29 21:11:07.057 DEBUG (SyncWorker_57) [custom_components.aula.client] Reusing existing token for widget 0030
2024-10-29 21:11:07.109 DEBUG (SyncWorker_57) [custom_components.aula.client] MU Opgaver status_code 200
2024-10-29 21:11:07.109 DEBUG (SyncWorker_57) [custom_components.aula.client] MU Opgaver response {"opgaver":[]}
2024-10-29 21:11:07.110 DEBUG (SyncWorker_57) [custom_components.aula.client] MU Opgaver result: 
2024-10-29 21:11:07.111 DEBUG (SyncWorker_57) [custom_components.aula.client] In the MU Opgaver flow
2024-10-29 21:11:07.111 DEBUG (SyncWorker_57) [custom_components.aula.client] Reusing existing token for widget 0030
2024-10-29 21:11:07.158 DEBUG (SyncWorker_57) [custom_components.aula.client] MU Opgaver status_code 200
2024-10-29 21:11:07.158 DEBUG (SyncWorker_57) [custom_components.aula.client] MU Opgaver response {"opgaver":[]}
2024-10-29 21:11:07.158 DEBUG (SyncWorker_57) [custom_components.aula.client] MU Opgaver result: 
2024-10-29 21:11:07.160 DEBUG (MainThread) [custom_components.aula.sensor] Finished fetching sensor data in 2.210 seconds (success: True)
2024-10-29 21:11:07.161 DEBUG (MainThread) [custom_components.aula.sensor] Setting state to n/a for child 111111111
2024-10-29 21:11:10.563 ERROR (MainThread) [frontend.js.modern.202410023] Uncaught error from Chrome 130.0.0.0 on Mac OS 10.15.7
NotSupportedError: Failed to execute 'define' on 'CustomElementRegistry': the name "mini-graph-card" has already been used with this registry
/hacsfiles/mini-graph-card/mini-graph-card-bundle.js:1:112575
/hacsfiles/mini-graph-card/mini-graph-card-bundle.js:1:18819
/hacsfiles/mini-graph-card/mini-graph-card-bundle.js:1:18824
/hacsfiles/mini-graph-card/mini-graph-card-bundle.js:1:112813
2024-10-29 21:11:10.563 ERROR (MainThread) [frontend.js.modern.202410023] Uncaught error from Chrome 130.0.0.0 on Mac OS 10.15.7
NotSupportedError: Failed to execute 'define' on 'CustomElementRegistry': the name "mmp-checkbox" has already been used with this registry
/hacsfiles/mini-media-player/mini-media-player-bundle.js:162:67
/hacsfiles/mini-media-player/mini-media-player-bundle.js:162:82
t (/hacsfiles/mini-media-player/mini-media-player-bundle.js:15:250)
/hacsfiles/mini-media-player/mini-media-player-bundle.js:707:170
```

**Comment by scaarup** [comment]
"Ugekalender" - hvad er det? 
Jf din log har du:
`2024-10-30 20:47:35.608 DEBUG (SyncWorker_19) [custom_components.aula.client] Widgets found: {'0029': 'MinUddannelse – Ugenoter', '0030': 'MinUddannelse - Opgaver', '0028': 'MinUddannelse – Forløb', '0047': 'Fravær - forældreindberetning', '0120': 'MinUddannelse - Meddelelsesbog'}`


"MinUddannelse - Opgaver" er understøttet af integrationen, men svaret er tomt - ser det ud til fra din log:
`MU Opgaver response {"opgaver":[]}
`
Har du noget data i Aula appen?

**Comment by sorenbache** [comment]
Jeg mente ugenoter eller ugeplan :) 

Der er faktisk kommet ugenoter efter den seneste version 0.1.45 kom. Så den har løst mit umiddelbare problem.
