### ISSUE TITLE
Får ingen data fra Aula

### ISSUE THREAD

**Issue by dennisroenn77** [scaarup/aula#191]
Hej, 

Tak for en fantastisk integration. Den hjælper SÅ meget i hverdagen.

Igår ca. kl. 21 mistede jeg alle sensorer mv. Jeg her gentagene gange forsøgt at fjerne både Aula fra HACS og selve integrationen, og installere igen. Jeg får nedenstående error log.

(Jeg har tjekket at mit Unilogin virker på Aula's hjemme side, så det er ikke et forkert pw jeg taster :-)
Sidste ting: Det er mit eget Unilogin jeg bruger ikke børnenes. Jeg formoder det er rigtigt.

**Please answer the following**
- Version of integration: 0.1.42
- Version of Home Assistant: 2024.10.4 (Core)
- [x ] I have more than one child
- [ ] My children are attending different schools / institutions

**REQUIRED! Provide debug log from the integration**
- Enable by adding the following to your configuration.yaml:
```
logger:
  default: info
  logs:
    custom_components.aula: debug
```
- Restart Home Assistant
- Capture all log lines (from the integration only), save it to a file and attach it to here.
- 
2024-10-30 10:55:15.421 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration aula which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-10-30 10:55:29.383 INFO (MainThread) [homeassistant.setup] Setting up aula
2024-10-30 10:55:29.383 INFO (MainThread) [homeassistant.setup] Setup of domain aula took 0.00 seconds
2024-10-30 10:55:29.384 INFO (MainThread) [custom_components.aula]
Aula integration, version: 0.1.42
https://github.com/scaarup/aula/issues
2024-10-30 10:55:29.398 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'aula' calls async_forward_entry_setup for integration, aula with title: Aula and entry_id: 01JBEDAFJ4V0S21SEM95WXA1SC, which is deprecated and will stop working in Home Assistant 2025.6, await async_forward_entry_setups instead at custom_components/aula/__init__.py, line 25: hass.async_create_task(, please create a bug report at https://github.com/scaarup/aula/issues
2024-10-30 10:55:36.540 INFO (MainThread) [homeassistant.components.sensor] Setting up aula.sensor
2024-10-30 10:55:36.541 DEBUG (SyncWorker_5) [custom_components.aula.client] is_logged_in? False
2024-10-30 10:55:36.542 DEBUG (SyncWorker_5) [custom_components.aula.client] Logging in
2024-10-30 10:55:41.379 DEBUG (SyncWorker_5) [custom_components.aula.client] Trying API at https://www.aula.dk/api/v19
2024-10-30 10:55:41.430 DEBUG (SyncWorker_5) [custom_components.aula.client] API was expected at https://www.aula.dk/api/v19 but responded with HTTP 410. The integration will automatically try a newer version and everything may work fine.
2024-10-30 10:55:41.430 DEBUG (SyncWorker_5) [custom_components.aula.client] Trying API at https://www.aula.dk/api/v20
2024-10-30 10:55:41.751 DEBUG (SyncWorker_5) [custom_components.aula.client] Found API on https://www.aula.dk/api/v20
2024-10-30 10:55:42.008 DEBUG (SyncWorker_5) [custom_components.aula.client] LOGIN: True
2024-10-30 10:55:42.008 DEBUG (SyncWorker_5) [custom_components.aula.client] Config - schoolschedule: True, config - ugeplaner: True
2024-10-30 10:55:42.009 DEBUG (SyncWorker_5) [custom_components.aula.client] Child ids and names: {xxx: 'xxx', xxx: 'xxxxx'}
2024-10-30 10:55:42.009 DEBUG (SyncWorker_5) [custom_components.aula.client] Child ids and institution names: {1877020: 'Skovlunde Skole – Rosenlund', 5240953: 'Skovlunde Skole – Rosenlund'}
2024-10-30 10:55:42.009 DEBUG (SyncWorker_5) [custom_components.aula.client] Institution codes: ['280564', 'G17685']
2024-10-30 10:55:42.103 DEBUG (SyncWorker_5) [custom_components.aula.client] Unable to retrieve presence data from Aula from child with id 1877020. Some data will be missing from sensor entities.
2024-10-30 10:55:42.231 DEBUG (SyncWorker_5) [custom_components.aula.client] Child ids and presence data status: {'1877020': 0, '5240953': 1}
2024-10-30 10:55:42.797 DEBUG (SyncWorker_5) [custom_components.aula.client] Fetching calendars...
2024-10-30 10:55:45.251 DEBUG (SyncWorker_5) [custom_components.aula.client] Widgets found: {'0004': 'Ugeplan forældre', '0119': 'Meebook overblik', '0047': 'Fravær - forældreindberetning', '0003': 'Ugens forløb - Meebook Forældre', '0019': 'Biblioteket', '0018': 'EasyIQ Links', '0024': 'Forældreportalen'}
2024-10-30 10:55:45.251 DEBUG (SyncWorker_5) [custom_components.aula.client] In the Meebook flow...
2024-10-30 10:55:45.251 DEBUG (SyncWorker_5) [custom_components.aula.client] Requesting new token for widget 0004
2024-10-30 10:55:45.586 DEBUG (SyncWorker_5) [custom_components.aula.client] Meebook ugeplan for xxx
2024-10-30 10:55:45.852 ERROR (MainThread) [custom_components.aula.sensor] Unexpected error fetching sensor data
File "/config/custom_components/aula/sensor.py", line 60, in async_update_data
File "/config/custom_components/aula/client.py", line 762, in update_data
File "/config/custom_components/aula/client.py", line 743, in ugeplan
2024-10-30 10:55:45.872 DEBUG (MainThread) [custom_components.aula.sensor] Finished fetching sensor data in 9.331 seconds (success: False)
2024-10-30 10:55:46.047 DEBUG (SyncWorker_10) [custom_components.aula.client] is_logged_in? True
2024-10-30 10:55:46.048 DEBUG (SyncWorker_10) [custom_components.aula.client] Child ids and names: {xxxx'}
2024-10-30 10:55:46.048 DEBUG (SyncWorker_10) [custom_components.aula.client] Child ids and institution names: {1877020: 'Skovlunde Skole – Rosenlund', 5240953: 'Skovlunde Skole – Rosenlund'}
2024-10-30 10:55:46.048 DEBUG (SyncWorker_10) [custom_components.aula.client] Institution codes: ['280564', 'G17685']
2024-10-30 10:55:46.143 DEBUG (SyncWorker_10) [custom_components.aula.client] Unable to retrieve presence data from Aula from child with id 1877020. Some data will be missing from sensor entities.
2024-10-30 10:55:46.274 DEBUG (SyncWorker_10) [custom_components.aula.client] Child ids and presence data status: {'1877020': 0, '5240953': 1}
2024-10-30 10:55:46.639 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform aula is taking over 10 seconds.
2024-10-30 10:55:47.911 DEBUG (SyncWorker_10) [custom_components.aula.client] Fetching calendars...
2024-10-30 10:55:50.130 DEBUG (SyncWorker_10) [custom_components.aula.client] In the Meebook flow...
2024-10-30 10:55:50.130 DEBUG (SyncWorker_10) [custom_components.aula.client] Reusing existing token for widget 0004
2024-10-30 10:55:50.298 DEBUG (SyncWorker_10) [custom_components.aula.client] Meebook ugeplan for Sofie Jørgensen-Rønn
2024-10-30 10:55:50.300 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up aula platform for sensor
File "/config/custom_components/aula/sensor.py", line 75, in async_setup_entry
File "/config/custom_components/aula/client.py", line 762, in update_data
File "/config/custom_components/aula/client.py", line 743, in ugeplan
2024-10-30 10:55:50.310 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that calls async_forward_entry_setup for integration aula with title: Aula and entry_id: 01JBEDAFJ4V0S21SEM95WXA1SC, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.

**Comment by Jogge** [comment]
Det er `ugeplaner` som fejler igen...

Indtil det er løst kan du slå ugeplaner fra under opsætningskonfigurationen, hvor du skal <ins>**undlade**</ins> at slå følgende til:

![image](https://github.com/user-attachments/assets/2eb47e96-9880-44b8-a797-872ae501d3cb)

Husk at slet din eksisterende opsætning først, så du ikke får duplicates:

![image](https://github.com/user-attachments/assets/2d0f57fa-600e-411b-817b-bbde06449a50)

**Comment by Oceanfarm** [comment]
> Det er `ugeplaner` som fejler igen...
> 
> Indtil det er løst kan du slå ugeplaner fra under opsætningskonfigurationen, hvor du skal **undlade** at slå følgende til:
> 
> ![image](https://private-user-images.githubusercontent.com/15981279/381888154-2eb47e96-9880-44b8-a797-872ae501d3cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNzIyMzEsIm5iZiI6MTczMDM3MTkzMSwicGF0aCI6Ii8xNTk4MTI3OS8zODE4ODgxNTQtMmViNDdlOTYtOTg4MC00NGI4LWE3OTctODcyYWU1MDFkM2NiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDEwNTIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyZjM1MWFmNDc3NzE4MGVhMmMyNjk5Zjc5YTE0N2FmNGJjZWIxOGEwMmZkZDA2YmRlYjVjN2Q4YzU4ODhmNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._GsJV7B8Sueu464STljcIMJ3-Jfr05ycv2BABY5CJn8)
> 
> Husk at slet din eksisterende opsætning først, så du ikke får duplicates:
> 
> ![image](https://private-user-images.githubusercontent.com/15981279/381889118-2d0f57fa-600e-411b-817b-bbde06449a50.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNzIyMzEsIm5iZiI6MTczMDM3MTkzMSwicGF0aCI6Ii8xNTk4MTI3OS8zODE4ODkxMTgtMmQwZjU3ZmEtNjAwZS00MTFiLTgxN2ItYmJkZTA2NDQ5YTUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDEwNTIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmYjkzOTNhOTIwNmRkOGU2ZjYyZTQ2MDNlMDlkMDU4NTdhNTAzMTQzZGUyY2I3MDc0ZTk4MjVjNzk0NWM3ZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sMUGBB0OCKmoVXEE3gmmj0Yavry2PpCt9ksX3Rml6Tc)

Ikke her. Den efter at have slettet enheden, finder den intet efter tilføjelsen på ny.

**Comment by scaarup** [comment]
Alle jer med problemer her, bruger I Meebook ('0004': 'Ugeplan forældre',) ?
Og er der problemer hos dem - får I data i Aula app'en uden problemer?

**Comment by Oceanfarm** [comment]
Har problemer både med ugeplan valgt til og fra.

Får data i Aula app uden problemer.

**Comment by scaarup** [comment]
> Har problemer både med ugeplan valgt til og fra.
> 
> Får data i Aula app uden problemer.

Der skal lidt debug log til, hvis vi skal kunne konstatere, at det er det samme problem som @dennisroenn77 har rapporteret her.

**Comment by dennisroenn77** [comment]
Hej Søren, 
Jeg kan bekæfte at løsningen med at undlade fluebenet i "Add ugeplaner as sensor attributes" virker. Efter en omgang slet og installere integrationen på ny, virker det igen. Dvs. jeg får kalenderen med skemaet oprettet, men givet, ingen ugeplaner (i sensorerne).

Et forsøg på lidt info som måske kan hjælpe til løsningen på problemet: Det ser ud til at i Aula app'en, at ugeplaner fungerer korrekt - både hvis man i menuen trykker "Ugeplan forældre" eller Meebook overblik. Jeg har indsat et par sceenshots fra appen herunder. 

Måske der er andre som kan sende deres debug log hvis i oplever samme fejl - altså at der ikke kan hentes data fra Ugeplan? Det vil sikkert også hjælpe.

Endnu engang, tak for en god integration :-)

![Screenshot_20241031_213052-EDIT-EDIT](https://github.com/user-attachments/assets/9cc18393-cbdf-41ad-a6cd-3dd84b35bfe1)
![Screenshot_20241031_213042-EDIT](https://github.com/user-attachments/assets/10beff54-3421-4605-839d-185c44b5e7c9)
![Screenshot_20241031_213306-EDIT](https://github.com/user-attachments/assets/c0cf7906-4eb5-4279-868d-4365ad4ed76e)

**Comment by poulpreben** [comment]
Jeg har haft debug slået til siden i går, og her er en fejl som måske kan hjælpe os videre:

```
2024-10-31 15:00:32.587 INFO (MainThread) [custom_components.aula] 
                _
     /\        | |
    /  \  _   _| | __ _
   / /\ \| | | | |/ _` |
  / ____ \ |_| | | (_| |
 /_/    \_\__,_|_|\__,_|
Aula integration, version: 0.1.42
This is a custom integration
If you have any issues with this you need to open an issue here:
https://github.com/scaarup/aula/issues
-------------------------------------------------------------------

2024-10-31 15:00:32.596 DEBUG (SyncWorker_5) [custom_components.aula.client] is_logged_in? False
2024-10-31 15:00:32.596 DEBUG (SyncWorker_5) [custom_components.aula.client] Logging in
2024-10-31 15:00:34.897 DEBUG (SyncWorker_5) [custom_components.aula.client] Trying API at https://www.aula.dk/api/v19
2024-10-31 15:00:34.939 DEBUG (SyncWorker_5) [custom_components.aula.client] API was expected at https://www.aula.dk/api/v19 but responded with HTTP 410. The integration will automatically try a newer version and everything may work fine.
2024-10-31 15:00:34.939 DEBUG (SyncWorker_5) [custom_components.aula.client] Trying API at https://www.aula.dk/api/v20
2024-10-31 15:00:35.146 DEBUG (SyncWorker_5) [custom_components.aula.client] Found API on https://www.aula.dk/api/v20
2024-10-31 15:00:36.980 DEBUG (SyncWorker_5) [custom_components.aula.client] LOGIN: True
2024-10-31 15:00:36.980 DEBUG (SyncWorker_5) [custom_components.aula.client] Config - schoolschedule: True, config - ugeplaner: True
2024-10-31 15:00:36.980 DEBUG (SyncWorker_5) [custom_components.aula.client] Child ids and names: {nnn: 'xxx'}
2024-10-31 15:00:36.980 DEBUG (SyncWorker_5) [custom_components.aula.client] Child ids and institution names: {nnn: 'Hanssted Skole'}
2024-10-31 15:00:36.980 DEBUG (SyncWorker_5) [custom_components.aula.client] Institution codes: ['nnn']
2024-10-31 15:00:39.392 DEBUG (SyncWorker_5) [custom_components.aula.client] Child ids and presence data status: {'nnn': 1}
2024-10-31 15:00:42.596 WARNING (MainThread) [homeassistant.components.sensor] Setup of sensor platform aula is taking over 10 seconds.
2024-10-31 15:01:00.882 ERROR (MainThread) [custom_components.aula.sensor] Unexpected error fetching sensor data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 271, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/aula/sensor.py", line 60, in async_update_data
    await hass.async_add_executor_job(client.update_data)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/aula/client.py", line 762, in update_data
    ugeplan(thisweek, "this")
  File "/config/custom_components/aula/client.py", line 743, in ugeplan
    ugep = ugep + task["author"] + "<br><br>"
                  ~~~~^^^^^^^^^^
KeyError: 'author'
2024-10-31 15:01:12.829 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up aula platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/aula/sensor.py", line 75, in async_setup_entry
    await hass.async_add_executor_job(client.update_data)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/aula/client.py", line 762, in update_data
    ugeplan(thisweek, "this")
  File "/config/custom_components/aula/client.py", line 743, in ugeplan
    ugep = ugep + task["author"] + "<br><br>"
                  ~~~~^^^^^^^^^^
KeyError: 'author'
2024-10-31 15:01:12.830 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that calls async_forward_entry_setup for integration aula with title: Aula and entry_id: 01JBHB6A9D7FYNPRDG4217FJCC, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.
Stack (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2223, in async_forward_entry_setup
    _report_non_awaited_platform_forwards(entry, "async_forward_entry_setup")
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1192, in _report_non_awaited_platform_forwards
    report(
  File "/usr/src/homeassistant/homeassistant/helpers/frame.py", line 155, in report
    _LOGGER.warning(msg, stack_info=True)
```

Jeg rettede følgende linje til, og nu virker det igen:

https://github.com/scaarup/aula/blob/07da541e2326bb9e4684812c45cd55264eaa74b5/custom_components/aula/client.py#L759

```python
author = task.get('author', "")
ugep = ugep + author + "<br><br>"
```

**Comment by Oceanfarm** [comment]
Jeg er måske ikke helt med. Du skriver at du rettede linjen (ental) til, men har tilføjet to linjer nedenfor?
Så du har skiftet linje 759 ud med de to linjer indført?
I så fald, virker det stadig ikke her...

**Comment by Oceanfarm** [comment]
2024-11-01 16:13:59.635 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up aula platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/aula/sensor.py", line 75, in async_setup_entry
    await hass.async_add_executor_job(client.update_data)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/aula/client.py", line 778, in update_data
    nextweek = now.strftime("%Y-W%W")
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/aula/client.py", line 759, in ugeplan
    author = task.get('author', "")
              ^^^^^^
NameError: name 'author' is not defined
2024-11-01 16:13:59.649 WARNING (MainThread) [homeassistant.helpers.frame] Detected code that calls async_forward_entry_setup for integration aula with title: Aula and entry_id: 01JBKSASVP0TRYKR45BEPE679M, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.

**Comment by poulpreben** [comment]
Det kommer lidt an på versionen om det præcist er linje 759. Kan du paste det, du har erstattet?

Du skal finde den linje hvor task["author"] indsættes i tekststrengen. Problemet (for mig) er at author ikke længere er med i task-objektet, så jeg har indført et check, som gør det til to linjer fremfor én.

**Comment by ckref** [comment]
Samme fejl her,  som er løst ved @poulpreben metode

**Comment by dennisroenn77** [comment]
Forsøgte @poulpreben løsningen, men uden held. Den virker ikke her.

![Skærmbillede 2024-11-02 212617](https://github.com/user-attachments/assets/648cc398-b2fb-42d4-84e5-2b09b561b2e7)
![Skærmbillede 2024-11-02 212448](https://github.com/user-attachments/assets/884500f1-3ad1-4280-a52b-3b8d39039f2c)

**Comment by poulpreben** [comment]
> Forsøgte @poulpreben løsningen, men uden held. Den virker ikke her.

Kan du bekræfte at du har genstartet efter du har foretaget ændringen? Hvis ja, kan du rulle ændringen tilbage, genstarte, og uploade nogle timers debug log? Dit problem må i så fald være et andet, så der er muligvis flere steder hvor vi med fordel kan bidrage med fejlhåndtering 😃

**Comment by kaelken** [comment]
Kan bekræfte løsningen som @poulpreben kom med, jeg får nu data ind.
@dennisroenn77 Har du husket at rette begge linjer da 744 tager author i stedet for task["author"] som den gjorde før. 
Vil tro at det skulle virke for dig også, da vi har børn samme sted :D

**Comment by Ronnie-J** [comment]
Jeg har samme problem. Jeg har med @poulpreben rettelse fået den til at hente data igen fra Aula, men ikke ugeplaner. Der fejler den fortsat. Vi anvender Meebook til ugeplaner på skolen.

**Comment by mjay9876** [comment]
Hej jeg har prøvet at gøre @poulpreben rettelse men får ingen data forsat

har vedhæfted debug og et par skærmudklip hvis der er en der kan hjælpe mig på rette vej :)
![config](https://github.com/user-attachments/assets/8e386b9d-812b-4abe-9449-8a00e492cbb1)
[debug.txt](https://github.com/user-attachments/files/17611223/debug.txt)
![Unavngivet](https://github.com/user-attachments/assets/c58a702a-cafc-4c91-a784-07b5028933e5)

**Comment by dennisroenn77** [comment]
Hej alle, 
Tak for god support :-) Efter jeg har indsat de 2 linier i client.py, har jeg genstartet hver gang. Endda afinstalleret både integration og HACS integrationen, men uden held. 
Nu prøvede jeg lige igen at "rense" det hele ud, genstarte og vente i 15 min. 
Herefter installerede jeg HACS integrationen igen, og så der lå en version 0.1.43 :-) Halleluja! Den tog jeg, MEN det virkede forsat ikke. :-( 
Jeg forsøgte med at indsætte de 2 linier @poulpreben foreslog, genstartede, og nu virker alt. Både kalender og ugeplan.
Jeg går nårmalt ikke i kirke om søndagen, men måske burde jeg - for mine bønner er hørt. 

Tak for en fantastik integration, nu kører det igen - i øvrigt med ChatGTP som oplæser :-)

**Comment by Oceanfarm** [comment]
> Det kommer lidt an på versionen om det præcist er linje 759. Kan du paste det, du har erstattet?
> 
> Du skal finde den linje hvor task["author"] indsættes i tekststrengen. Problemet (for mig) er at author ikke længere er med i task-objektet, så jeg har indført et check, som gør det til to linjer fremfor én.

![image](https://github.com/user-attachments/assets/b67b970c-18e8-4c16-8ed1-7ad7d1640aba)

**Comment by Oceanfarm** [comment]
Hvis jeg fravælger "Tilføj ugeplaner som sensor attributter?", så virker alt undtagen ugeplaner.

`2024-11-04 09:31:25.286 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up aula platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/aula/sensor.py", line 75, in async_setup_entry
    await hass.async_add_executor_job(client.update_data)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/aula/client.py", line 777, in update_data
    ugeplan(thisweek, "this")
  File "/config/custom_components/aula/client.py", line 760, in ugeplan
    r"([0-9]+)(\.)", r"\1\.", task["content"]
                              ~~~~^^^^^^^^^^^
KeyError: 'content'`

**Comment by mrryel** [comment]
rettede client.py linje 744 (lidt forskelligt fra install til intall) til @poulpreben lille fix:

_author = task.get('author', "")
ugep = ugep + author + "<br><br>"_

og vupti, så virkede det igen. Tak @poulpreben <3

**Comment by SkinnyGnome** [comment]
> Hej alle, Tak for god support :-) Efter jeg har indsat de 2 linier i client.py, har jeg genstartet hver gang. Endda afinstalleret både integration og HACS integrationen, men uden held. Nu prøvede jeg lige igen at "rense" det hele ud, genstarte og vente i 15 min. Herefter installerede jeg HACS integrationen igen, og så der lå en version 0.1.43 :-) Halleluja! Den tog jeg, MEN det virkede forsat ikke. :-( Jeg forsøgte med at indsætte de 2 linier @poulpreben foreslog, genstartede, og nu virker alt. Både kalender og ugeplan. Jeg går nårmalt ikke i kirke om søndagen, men måske burde jeg - for mine bønner er hørt.
> 
> Tak for en fantastik integration, nu kører det igen - i øvrigt med ChatGTP som oplæser :-)

Jeg forsøgte med denne løsning, men uden held desværre.

Istedet for fejlen:
File "/config/custom_components/aula/client.py", line 759, in ugeplan
author = task.get('author', "")

Får jeg nu:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/aula/sensor.py", line 75, in async_setup_entry
    await hass.async_add_executor_job(client.update_data)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  **File "/config/custom_components/aula/client.py", line 779, in update_data
    ugeplan(thisweek, "this")
  File "/config/custom_components/aula/client.py", line 762, in ugeplan
    r"([0-9]+)(\.)", r"\1\.", task["content"]**


Jeg har kigget efter om indrykninger osv. er korrekt og der ser fint ud.

**Comment by Jogge** [comment]
Hvis I har fundet en løsning på problemet, vil det være en stor hjælp for projektet, hvis I opretter et Pull Request. Det er langt bedre end at sende andre på jagt efter, hvilke ændringer de skal lave selv – på den måde bliver løsningen tilgængelig for alle.

Nu bruger I jo selv dette open source-projekt, så det mindste, man kan gøre, er at give lidt tilbage i stedet for blot at holde løsningen for sig selv...

**Comment by SkinnyGnome** [comment]
Jeg fik leget lidt med debugging og fandt frem til fejlen med "task["content"]"
Det viser sig at content ikke findes hvis task typen er "assignment".

Da assignement ikke indeholder key content mend title, har jeg indsat følgende.

```
                                        author = task.get('author', "")
                                        ugep = ugep + author + "<br><br>"
                                        if task["type"] == "comment" or task["type"] == "task":
                                            content = re.sub(
                                                r"([0-9]+)(\.)", r"\1\.", task["content"]
                                            )
                                        elif task["type"] == "assignment":
                                            content = re.sub(
                                                r"([0-9]+)(\.)", r"\1\.", task["title"]
                                            )
                                        ugep = ugep + content + "<br><br>"
```

![image](https://github.com/user-attachments/assets/053233ba-e850-47df-b90c-95d75de6d190)


Jeg når desværre nok ikke at lave Pull Requests hen over denne weekend, da den er maks presset i forvejen.
@scaarup: Måske du kan se om overstående giver mening at smide ind?

**Comment by poulpreben** [comment]
Jeg afventede lige feedback før jeg ville oprette PR. Det er hermed gjort, inkl. @SkinnyGnome ændringer.

**Comment by scaarup** [comment]
Blev det her problem egentlig løst? PR er merged og der kom en ny version.

**Comment by Jogge** [comment]
Ja, problemet blev løst i #192.
