### ISSUE TITLE
Problem med kalender

### ISSUE THREAD

**Issue by norjen** [scaarup/aula#23]
Super arbejde med denne app.

Udover jeg også ser fejlen som rapporteret i Issue #17 få jeg også denne fejl når jeg forsøger at importere kalender. I forbindelse med aktivering af kalenderen oplever jeg også at Home Assistant hænger i 5 - 10 sekunder, det har jeg ikke oplevet før.

Logger: homeassistant.components.calendar
Source: custom_components/aula/calendar.py:39
Integration: Calendar (documentation, issues)
First occurred: 9:42:40 PM (2 occurrences)
Last logged: 9:55:10 PM

Error while setting up aula platform for calendar
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/aula/calendar.py", line 39, in async_setup_entry
    for i, child in enumerate(client._children):
AttributeError: 'Client' object has no attribute '_children'

**Comment by scaarup** [comment]
Der er noget data, der ikke blev hentet som forventet. Prøv at genstart ha engang, så lykkes det forhåbentlig. 

Jeg skal nok snart finde en pænere måde at få hentet data på.

**Comment by scaarup** [comment]
@norjen hvad er status?

**Comment by norjen** [comment]
Efter en ny release - prøvede jeg at slette integrationen og sætte den op igen.
Derefter virker kalenderen som forventet.

Hvis jeg derimod også forsøger at tilvælge ugeplaner kommer enititeten aldrig op.

**Comment by norjen** [comment]
Det ligner rigtig meget den samme fejl:
Logger: homeassistant.components.sensor
Source: custom_components/aula/client.py:119
Integration: Sensor (documentation, issues)
First occurred: 11:24:30 AM (1 occurrences)
Last logged: 11:24:30 AM

Error while setting up aula platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/aula/sensor.py", line 55, in async_setup_entry
    await hass.async_add_executor_job(client.update_data)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/aula/client.py", line 129, in update_data
    ugeplan(thisweek,"this")
  File "/config/custom_components/aula/client.py", line 119, in ugeplan
    for person in ugeplaner.json()["personer"]:
KeyError: 'personer'
