### ISSUE TITLE
Error while setitng up platform....

### ISSUE THREAD

**Issue by Johndolk** [scaarup/aula#33]
Har lidt bøvl med at få den til at virke :(
Den melder to fejl:

Error while setting up aula platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/aula/sensor.py", line 55, in async_setup_entry
    await hass.async_add_executor_job(client.update_data)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/aula/client.py", line 133, in update_data
    ugeplan(thisweek,"this")
  File "/config/custom_components/aula/client.py", line 123, in ugeplan
    for person in ugeplaner.json()["personer"]:
KeyError: 'personer'

Og denne:

Unexpected error fetching sensor data: 'personer'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 164, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/aula/sensor.py", line 40, in async_update_data
    await hass.async_add_executor_job(client.update_data)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/aula/client.py", line 133, in update_data
    ugeplan(thisweek,"this")
  File "/config/custom_components/aula/client.py", line 123, in ugeplan
    for person in ugeplaner.json()["personer"]:
KeyError: 'personer'

**Comment by scaarup** [comment]
Hej. Det lugter rigtig meget af issue #17 - du har ugenoter fra Meebook.

**Comment by scaarup** [comment]
Dup af #17
