### ISSUE TITLE
Get status "n/a" in entity :(

### ISSUE THREAD

**Issue by jascdk** [scaarup/aula#35]
Since last update I don't have the come/leaving sensor anymore.

Debug log says: 

Logger: homeassistant.components.sensor
Source: custom_components/aula/sensor.py:154 
Integration: Sensor (documentation, issues) 
First occurred: 15.06.25 (2 occurrences) 
Last logged: 15.06.25

Error adding entities for domain sensor with platform aula
Error while setting up aula platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 503, in _async_add_entity
    if entity.unique_id is not None:
  File "/config/custom_components/aula/sensor.py", line 154, in unique_id
    _LOGGER.debug("Unique ID for "+name+": "+"aula"+str(uid))
UnboundLocalError: local variable 'name' referenced before assignment

**Comment by scaarup** [comment]
@jascdk der er ikke en eneste debug log linje - er du sikker på, at du har slået det til?

configuration.yaml:
```
logger:
  default: info
  logs:
    custom_components.aula: debug
```
evt. kan du prøve bare at fjerne den linje 154 i sensor.py - det er den, der fejler ovenstående.

**Comment by jascdk** [comment]
2022-11-21 19:10:43.369 DEBUG (MainThread) [custom_components.aula.calendar] 0 no client._children ... yet
2022-11-21 19:10:43.372 WARNING (MainThread) [homeassistant.util.async_] Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for aula doing blocking calls at custom_components/aula/calendar.py, line 38: time.sleep(0.400)
2022-11-21 19:10:43.778 DEBUG (MainThread) [custom_components.aula.calendar] 1 no client._children ... yet
2022-11-21 19:10:43.780 WARNING (MainThread) [homeassistant.util.async_] Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for aula doing blocking calls at custom_components/aula/calendar.py, line 38: time.sleep(0.400)
2022-11-21 19:10:44.184 DEBUG (MainThread) [custom_components.aula.calendar] 2 no client._children ... yet
2022-11-21 19:10:44.192 WARNING (MainThread) [homeassistant.util.async_] Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for aula doing blocking calls at custom_components/aula/calendar.py, line 38: time.sleep(0.400)
2022-11-21 19:10:44.595 DEBUG (MainThread) [custom_components.aula.calendar] 3 no client._children ... yet
2022-11-21 19:10:44.597 WARNING (MainThread) [homeassistant.util.async_] Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for aula doing blocking calls at custom_components/aula/calendar.py, line 38: time.sleep(0.400)
2022-11-21 19:10:45.000 DEBUG (MainThread) [custom_components.aula.calendar] 4 no client._children ... yet
2022-11-21 19:10:45.002 WARNING (MainThread) [homeassistant.util.async_] Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for aula doing blocking calls at custom_components/aula/calendar.py, line 38: time.sleep(0.400)
2022-11-21 19:10:45.403 DEBUG (MainThread) [custom_components.aula.calendar] 5 no client._children ... yet
2022-11-21 19:10:45.405 WARNING (MainThread) [homeassistant.util.async_] Detected blocking call to sleep inside the event loop. This is causing stability issues. Please report issue to the custom integration author for aula doing blocking calls at custom_components/aula/calendar.py, line 38: time.sleep(0.400)
2022-11-21 19:10:45.531 DEBUG (SyncWorker_5) [custom_components.aula.client] LOGIN: True
2022-11-21 19:10:45.702 WARNING (SyncWorker_5) [custom_components.aula.client] Unable to retrieve presence data from Aula. Some data will be missing from sensor entities.
2022-11-21 19:10:45.707 DEBUG (SyncWorker_5) [custom_components.aula.client] Fetching calendars...
2022-11-21 19:10:45.707 DEBUG (SyncWorker_5) [custom_components.aula.client] Calendar post-data: {"instProfileIds":[2668336,3457800],"resourceIds":[],"start":"2022-11-21 00:00:00.0000+0000","end":"2022-12-05 00:00:00.0000+0000"}
2022-11-21 19:10:45.808 DEBUG (MainThread) [custom_components.aula.calendar] Got client._children, breaking

**Comment by jascdk** [comment]
er det det her? Det ændrede ikke noget ved at slette linjerne som beskrevet

**Comment by Uberpainer** [comment]
Jeg får samme fejl, selv ugeplan kommer fint ud.

Jeg prøver lige aktiverer debug log, venter tilbage igen.

2022-11-21 20:41:21.296 WARNING (SyncWorker_11) [custom_components.aula.client] Unable to retrieve presence data from Aula. Some data will be missing from sensor entities.
2022-11-21 20:41:22.346 WARNING (SyncWorker_8) [custom_components.aula.client] Unable to retrieve presence data from Aula. Some data will be missing from sensor entities.
2022-11-21 20:41:22.733 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform aula
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 503, in _async_add_entity
if entity.unique_id is not None:
File "/config/custom_components/aula/sensor.py", line 154, in unique_id
_LOGGER.debug("Unique ID for "+name+": "+"aula"+str(uid))
UnboundLocalError: local variable 'name' referenced before assignment
2022-11-21 20:41:22.739 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up aula platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 503, in _async_add_entity
if entity.unique_id is not None:
File "/config/custom_components/aula/sensor.py", line 154, in unique_id
_LOGGER.debug("Unique ID for "+name+": "+"aula"+str(uid))
UnboundLocalError: local variable 'name' referenced before assignment
2022-11-21 20:41:32.164 WARNING (SyncWorker_7) [custom_components.aula.client] Unable to retrieve presence data from Aula. Some data will be missing from sensor entities.

**Comment by Uberpainer** [comment]
2022-11-21 20:46:51.963 INFO (MainThread) [custom_components.aula]
_
/\ | |
/ \ _ _| | __ _
/ /\ \| | | | |/ _` |
/ ____ \ |_| | | (_| |
/_/ \_\__,_|_|\__,_|
Aula integration, version: 0.1.19
This is a custom integration
If you have any issues with this you need to open an issue here:
https://github.com/scaarup/aula/issues

2022-11-21 20:46:51.996 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.aula
2022-11-21 20:46:52.149 DEBUG (SyncWorker_0) [custom_components.aula.client] self._schoolschedule False
2022-11-21 20:46:52.149 DEBUG (SyncWorker_0) [custom_components.aula.client] self._ugeplan True
2022-11-21 20:46:52.149 DEBUG (SyncWorker_0) [custom_components.aula.client] Presence module: 0
2022-11-21 20:46:52.149 DEBUG (SyncWorker_0) [custom_components.aula.client] is_logged_in? False
2022-11-21 20:46:52.149 DEBUG (SyncWorker_0) [custom_components.aula.client] Logging in
2022-11-21 20:46:54.575 DEBUG (SyncWorker_0) [custom_components.aula.client] LOGIN: True
2022-11-21 20:46:54.999 DEBUG (SyncWorker_0) [custom_components.aula.client] guardian :ande87h0
2022-11-21 20:46:55.187 DEBUG (SyncWorker_0) [custom_components.aula.client] ugeplaner status_code 200
2022-11-21 20:46:55.188 DEBUG (SyncWorker_0) [custom_components.aula.client] ugeplaner response {"personer":[{"navn":"Asger Engelund Jensen","id":2924066,"uniLogin":"asge5570","institutioner":[{"navn":"Sønderbroskolen","kode":851031,"ugebreve":[{"tilknytningId":248693,"tilknytningNavn":"0B","indhold":"<p>Uge 47 (d.21/11-25/11)</p><p><strong>Mandag:</strong> Matematik, hop om bord(bogstavet N).</p><p><strong>Tirsdag:</strong> Matematik, b&oslash;rnestavning.</p><p><strong>Onsdag: </strong>Hop om bord(bogstavet K), B&oslash;rnestavning, legetime.</p><p><strong>Torsdag:</strong> Matematik, ugeskema med forskellige dansk og matematik v&aelig;rksteder.</p><p><strong>Fredag:</strong> juleklippedag. vi klipper, klistre og pynter klassen og d&oslash;ren. Skolen giver &aelig;bleskiver og juice.&nbsp;</p>","uge":47,"sortOrder":0}],"forloeb":[]}]}]}
2022-11-21 20:46:55.225 DEBUG (SyncWorker_0) [custom_components.aula.client] ugeplaner status_code 200
2022-11-21 20:46:55.225 DEBUG (SyncWorker_0) [custom_components.aula.client] ugeplaner response {"personer":[]}
2022-11-21 20:46:56.055 DEBUG (MainThread) [custom_components.aula.sensor] Finished fetching sensor data in 3.907 seconds (success: True)
2022-11-21 20:46:56.088 DEBUG (SyncWorker_7) [custom_components.aula.client] self._schoolschedule False
2022-11-21 20:46:56.088 DEBUG (SyncWorker_7) [custom_components.aula.client] self._ugeplan True
2022-11-21 20:46:56.088 DEBUG (SyncWorker_7) [custom_components.aula.client] Presence module: 0
2022-11-21 20:46:56.219 DEBUG (SyncWorker_7) [custom_components.aula.client] is_logged_in? True
2022-11-21 20:46:56.629 WARNING (SyncWorker_7) [custom_components.aula.client] Unable to retrieve presence data from Aula. Some data will be missing from sensor entities.
2022-11-21 20:46:56.913 DEBUG (SyncWorker_7) [custom_components.aula.client] guardian :ande87h0
2022-11-21 20:46:57.039 DEBUG (SyncWorker_7) [custom_components.aula.client] ugeplaner status_code 200
2022-11-21 20:46:57.040 DEBUG (SyncWorker_7) [custom_components.aula.client] ugeplaner response {"personer":[{"navn":"Asger Engelund Jensen","id":2924066,"uniLogin":"asge5570","institutioner":[{"navn":"Sønderbroskolen","kode":851031,"ugebreve":[{"tilknytningId":248693,"tilknytningNavn":"0B","indhold":"<p>Uge 47 (d.21/11-25/11)</p><p><strong>Mandag:</strong> Matematik, hop om bord(bogstavet N).</p><p><strong>Tirsdag:</strong> Matematik, b&oslash;rnestavning.</p><p><strong>Onsdag: </strong>Hop om bord(bogstavet K), B&oslash;rnestavning, legetime.</p><p><strong>Torsdag:</strong> Matematik, ugeskema med forskellige dansk og matematik v&aelig;rksteder.</p><p><strong>Fredag:</strong> juleklippedag. vi klipper, klistre og pynter klassen og d&oslash;ren. Skolen giver &aelig;bleskiver og juice.&nbsp;</p>","uge":47,"sortOrder":0}],"forloeb":[]}]}]}
2022-11-21 20:46:57.077 DEBUG (SyncWorker_7) [custom_components.aula.client] ugeplaner status_code 200
2022-11-21 20:46:57.077 DEBUG (SyncWorker_7) [custom_components.aula.client] ugeplaner response {"personer":[]}
2022-11-21 20:47:00.272 DEBUG (MainThread) [custom_components.aula.sensor] in loop {'id': 3829359, 'profileId': 1734528, 'uniPersonId': 3856763, 'firstName': 'Asger Engelund', 'lastName': 'Jensen', 'fullName': 'Asger Engelund Jensen', 'shortName': 'AEJ', 'role': 'child', 'mailBoxId': 5348195, 'institution': {'institutionCode': '851031', 'institutionName': 'Sønderbroskolen', 'municipalityCode': '851', 'municipalityName': 'Aalborg', 'type': 'School', 'administrativeAuthority': {'id': 1425, 'name': 'Sønderbroskolen', 'institutionCodes': []}}, 'gender': 'M', 'profilePicture': {'id': 1370940, 'key': '1660219438/1195/eca45ec4.png', 'bucket': 'aula-prod-media', 'isImageScalingPending': False, 'url': 'https://media-prod.aula.dk/1660219438/1195/eca45ec4_400x400.png?response-content-disposition=attachment%3Bfilename%3D%22eca45ec4_400x400.png%22&Expires=1669060800&Signature=bg9GtKOgRZGzVLGjO323V-dpOIs-TaNWvljrBenkXHPR5e9P9CbcSbKO9BRySC8G0uUqTINq5SjnQHiI9g~uApSPoxD5JIs8hZANz6CVUuOcKADW2JR8SnHp8HuJ0xvOhDCCJP8EFp6g8zb4Lx1dyyFuROPJ9X7cm-gddGS1fkFmDMgHsWhECMNNajFkriWZkXMaOfeF-9zp1fxe0bCAVv78Fu5jJog-c5toqvscU-ePllWH4St-~FdzWdAp1hlyUBXLf~udcggNMC7BWbfyE1wXa55XRkZj7Cyy37OpPmIkqRi~7YuB~CppolK2Ed5qG089~tCklkn7OPaz3eaNeg__&Key-Pair-Id=APKAILBPECUQMHIBROXQ'}, 'mainGroupName': '0B', 'metadata': '0B'}
2022-11-21 20:47:00.272 DEBUG (MainThread) [custom_components.aula.sensor] trying to match 3829359 with 3829359
2022-11-21 20:47:00.272 DEBUG (MainThread) [custom_components.aula.sensor] MATCH
2022-11-21 20:47:00.273 DEBUG (MainThread) [custom_components.aula.sensor] Unique ID for Asger Engelund: aula3829359
2022-11-21 20:47:00.273 DEBUG (MainThread) [custom_components.aula.sensor] in loop {'id': 3829359, 'profileId': 1734528, 'uniPersonId': 3856763, 'firstName': 'Asger Engelund', 'lastName': 'Jensen', 'fullName': 'Asger Engelund Jensen', 'shortName': 'AEJ', 'role': 'child', 'mailBoxId': 5348195, 'institution': {'institutionCode': '851031', 'institutionName': 'Sønderbroskolen', 'municipalityCode': '851', 'municipalityName': 'Aalborg', 'type': 'School', 'administrativeAuthority': {'id': 1425, 'name': 'Sønderbroskolen', 'institutionCodes': []}}, 'gender': 'M', 'profilePicture': {'id': 1370940, 'key': '1660219438/1195/eca45ec4.png', 'bucket': 'aula-prod-media', 'isImageScalingPending': False, 'url': 'https://media-prod.aula.dk/1660219438/1195/eca45ec4_400x400.png?response-content-disposition=attachment%3Bfilename%3D%22eca45ec4_400x400.png%22&Expires=1669060800&Signature=bg9GtKOgRZGzVLGjO323V-dpOIs-TaNWvljrBenkXHPR5e9P9CbcSbKO9BRySC8G0uUqTINq5SjnQHiI9g~uApSPoxD5JIs8hZANz6CVUuOcKADW2JR8SnHp8HuJ0xvOhDCCJP8EFp6g8zb4Lx1dyyFuROPJ9X7cm-gddGS1fkFmDMgHsWhECMNNajFkriWZkXMaOfeF-9zp1fxe0bCAVv78Fu5jJog-c5toqvscU-ePllWH4St-~FdzWdAp1hlyUBXLf~udcggNMC7BWbfyE1wXa55XRkZj7Cyy37OpPmIkqRi~7YuB~CppolK2Ed5qG089~tCklkn7OPaz3eaNeg__&Key-Pair-Id=APKAILBPECUQMHIBROXQ'}, 'mainGroupName': '0B', 'metadata': '0B'}
2022-11-21 20:47:00.273 DEBUG (MainThread) [custom_components.aula.sensor] trying to match 3829359 with 3829359
2022-11-21 20:47:00.273 DEBUG (MainThread) [custom_components.aula.sensor] MATCH
2022-11-21 20:47:00.273 DEBUG (MainThread) [custom_components.aula.sensor] Unique ID for Asger Engelund: aula3829359
2022-11-21 20:47:00.273 DEBUG (MainThread) [custom_components.aula.sensor] in loop {'id': 3829359, 'profileId': 1734528, 'uniPersonId': 3856763, 'firstName': 'Asger Engelund', 'lastName': 'Jensen', 'fullName': 'Asger Engelund Jensen', 'shortName': 'AEJ', 'role': 'child', 'mailBoxId': 5348195, 'institution': {'institutionCode': '851031', 'institutionName': 'Sønderbroskolen', 'municipalityCode': '851', 'municipalityName': 'Aalborg', 'type': 'School', 'administrativeAuthority': {'id': 1425, 'name': 'Sønderbroskolen', 'institutionCodes': []}}, 'gender': 'M', 'profilePicture': {'id': 1370940, 'key': '1660219438/1195/eca45ec4.png', 'bucket': 'aula-prod-media', 'isImageScalingPending': False, 'url': 'https://media-prod.aula.dk/1660219438/1195/eca45ec4_400x400.png?response-content-disposition=attachment%3Bfilename%3D%22eca45ec4_400x400.png%22&Expires=1669060800&Signature=bg9GtKOgRZGzVLGjO323V-dpOIs-TaNWvljrBenkXHPR5e9P9CbcSbKO9BRySC8G0uUqTINq5SjnQHiI9g~uApSPoxD5JIs8hZANz6CVUuOcKADW2JR8SnHp8HuJ0xvOhDCCJP8EFp6g8zb4Lx1dyyFuROPJ9X7cm-gddGS1fkFmDMgHsWhECMNNajFkriWZkXMaOfeF-9zp1fxe0bCAVv78Fu5jJog-c5toqvscU-ePllWH4St-~FdzWdAp1hlyUBXLf~udcggNMC7BWbfyE1wXa55XRkZj7Cyy37OpPmIkqRi~7YuB~CppolK2Ed5qG089~tCklkn7OPaz3eaNeg__&Key-Pair-Id=APKAILBPECUQMHIBROXQ'}, 'mainGroupName': '0B', 'metadata': '0B'}
2022-11-21 20:47:00.273 DEBUG (MainThread) [custom_components.aula.sensor] trying to match 3829359 with 3829359
2022-11-21 20:47:00.273 DEBUG (MainThread) [custom_components.aula.sensor] MATCH
2022-11-21 20:47:00.273 DEBUG (MainThread) [custom_components.aula.sensor] Unique ID for Asger Engelund: aula3829359
2022-11-21 20:47:00.273 DEBUG (MainThread) [custom_components.aula.sensor] Could not get ugeplan for next week for child Asger. Perhaps not available yet or you have not enabled ugeplan
2022-11-21 20:47:00.273 DEBUG (MainThread) [custom_components.aula.sensor] in loop {'id': 3829359, 'profileId': 1734528, 'uniPersonId': 3856763, 'firstName': 'Asger Engelund', 'lastName': 'Jensen', 'fullName': 'Asger Engelund Jensen', 'shortName': 'AEJ', 'role': 'child', 'mailBoxId': 5348195, 'institution': {'institutionCode': '851031', 'institutionName': 'Sønderbroskolen', 'municipalityCode': '851', 'municipalityName': 'Aalborg', 'type': 'School', 'administrativeAuthority': {'id': 1425, 'name': 'Sønderbroskolen', 'institutionCodes': []}}, 'gender': 'M', 'profilePicture': {'id': 1370940, 'key': '1660219438/1195/eca45ec4.png', 'bucket': 'aula-prod-media', 'isImageScalingPending': False, 'url': 'https://media-prod.aula.dk/1660219438/1195/eca45ec4_400x400.png?response-content-disposition=attachment%3Bfilename%3D%22eca45ec4_400x400.png%22&Expires=1669060800&Signature=bg9GtKOgRZGzVLGjO323V-dpOIs-TaNWvljrBenkXHPR5e9P9CbcSbKO9BRySC8G0uUqTINq5SjnQHiI9g~uApSPoxD5JIs8hZANz6CVUuOcKADW2JR8SnHp8HuJ0xvOhDCCJP8EFp6g8zb4Lx1dyyFuROPJ9X7cm-gddGS1fkFmDMgHsWhECMNNajFkriWZkXMaOfeF-9zp1fxe0bCAVv78Fu5jJog-c5toqvscU-ePllWH4St-~FdzWdAp1hlyUBXLf~udcggNMC7BWbfyE1wXa55XRkZj7Cyy37OpPmIkqRi~7YuB~CppolK2Ed5qG089~tCklkn7OPaz3eaNeg__&Key-Pair-Id=APKAILBPECUQMHIBROXQ'}, 'mainGroupName': '0B', 'metadata': '0B'}
2022-11-21 20:47:00.273 DEBUG (MainThread) [custom_components.aula.sensor] trying to match 4016098 with 3829359
2022-11-21 20:47:00.344 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform aula
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 503, in _async_add_entity
if entity.unique_id is not None:
File "/config/custom_components/aula/sensor.py", line 154, in unique_id
_LOGGER.debug("Unique ID for "+name+": "+"aula"+str(uid))
UnboundLocalError: local variable 'name' referenced before assignment
2022-11-21 20:47:00.477 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up aula platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 503, in _async_add_entity
if entity.unique_id is not None:
File "/config/custom_components/aula/sensor.py", line 154, in unique_id
_LOGGER.debug("Unique ID for "+name+": "+"aula"+str(uid))
UnboundLocalError: local variable 'name' referenced before assignment

**Comment by Uberpainer** [comment]
Umiddelbart kan jeg godt hive presence data ud på min søn. Kan årsagen være jeg har to sønner i systemet den en som er skolebarn og den anden som går dagpleje. Kun den ældste har "Komme/Gå" funktionen aktiveret.


https://www.aula.dk/api/v14?method=presence.getDailyOverview&childIds[]=3829359

{"status":{"code":0,"message":"OK"},"data":[{"id":1173740,"institutionProfile":{"profileId":1734528,"id":3829359,"institutionCode":"851031","institutionName":"S\u00f8nderbroskolen","role":"child","name":"Asger Engelund Jensen","profilePicture":{"id":1370940,"key":"1660219438\/1195\/eca45ec4.png","bucket":"aula-prod-media","isImageScalingPending":false,"url":"https:\/\/media-prod.aula.dk\/1660219438\/1195\/eca45ec4_400x400.png?response-content-disposition=attachment%3Bfilename%3D%22eca45ec4_400x400.png%22&Expires=1669064400&Signature=b2QwekKBNwTgGLlwsiPGs1BCaUWdtPrbX2ON7~SINhElBvALfYVD1CEuPP~8~9SZMXmzjpZVDcrTJus9TD18bMwsvNzzPnYXG1HeF2XOPsXxlCTVxmhYCYyvJd3zrKNt7mwBJlgiJA8QvCbIeXg8pxBP8RwxHy0wKNuiohxIWYllhYkPpQfsoHtAc4JOw7VxrH-kAdXNmHlchRiCzqM1-H79HpbUYgTMla839Y98Y6w4QdDI60hbc6Xpc44Ev-ftMd9mNLQN1MEfsCq7QESu1Zpzm64l6hfjQoZAZrJJHtS6BeQD3AvnWpW1Mas1A0~5Qhl2HGudCSNFuMnDLFChzA__&Key-Pair-Id=APKAILBPECUQMHIBROXQ"},"mainGroup":null,"shortName":"AEJ","institutionRole":"early-student","metadata":"0B"},"mainGroup":{"id":727979,"name":"0B","institutionCode":"851031","institutionName":"S\u00f8nderbroskolen","mainGroup":true,"uniGroupType":"Hovedgruppe","isDeactivated":false,"allowMembersToBeShown":true},"status":8,"location":null,"sleepIntervals":[],"checkInTime":"07:32:53","checkOutTime":"14:56:56","editablePresenceStates":[],"isDefaultEntryTime":true,"isDefaultExitTime":true,"isPlannedTimesOutsideOpeningHours":false,"activityType":0,"entryTime":"05:00:00","exitTime":"23:59:00","exitWith":null,"comment":null,"spareTimeActivity":null,"selfDeciderStartTime":null,"selfDeciderEndTime":null}],"version":14,"module":"presence","method":"getDailyOverview"}

**Comment by jascdk** [comment]
Det samme er lidt gældende i mit tilfælde. Her er det dog kun vor yngste søn i børnehaven, som har komme gå funktion. Den ældste i 1 klasse i folkeskolen har ikke komme gå (fanme noget rod at de ikke kobler det sammen). Men jeg kunne før opdateringen også se den ældstes kalender (skema) - det kan jeg ikke mere

**Comment by scaarup** [comment]
Ja det er god info @Uberpainer og @jascdk - tak.

Kan I også bekræfte, at det hele virkede fint før seneste version?

**Comment by Uberpainer** [comment]
Jeg har ikke brugt seneste version men har kun brugt denne integration uden problemer:
https://github.com/JBoye/HA-Aula

**Comment by scaarup** [comment]
> Jeg har ikke brugt seneste version men har kun brugt denne integration uden problemer: https://github.com/JBoye/HA-Aula
> 
> Skal jeg prøve downgrade og i givel fald til hvilken version?

Ja det kunne være interessant at vide om 0.1.15 virkede. Fordi så er det et problem, der er introduceret med 0.1.19 og noget logik der.

**Comment by scaarup** [comment]
Jeg har lige push'et en branch hvor vi sætter "presence" modulet per barn i stedet for globalt - hvilket jo giver rigtig god mening.
https://github.com/scaarup/aula/tree/35-get-status-na-in-entity
Nogen der vil give det et skud?

**Comment by Uberpainer** [comment]
> Jeg har lige push'et en branch hvor vi sætter "presence" modulet per barn i stedet for globalt - hvilket jo giver rigtig god mening. https://github.com/scaarup/aula/tree/35-get-status-na-in-entity Nogen der vil give det et skud?

Så har jeg tetset med det nævnte branch og nu bliver presence returneret :)

**Comment by scaarup** [comment]
> > Jeg har lige push'et en branch hvor vi sætter "presence" modulet per barn i stedet for globalt - hvilket jo giver rigtig god mening. https://github.com/scaarup/aula/tree/35-get-status-na-in-entity Nogen der vil give det et skud?
> 
> Så har jeg tetset med det nævnte branch og nu bliver presence returneret :)

Fedt, tak 🙂. Og for dit barn i dagpleje, er state blot "n/a"?

**Comment by Uberpainer** [comment]
Korrekt :)

**Comment by jascdk** [comment]
> Ja det er god info @Uberpainer og @jascdk - tak.
> 
> Kan I også bekræfte, at det hele virkede fint før seneste version?

Alt virkede før ja - jeg har lige prøvet at installere din nye branch - syntes ikke det ændrer sig - skal jeg bruge sidst nyeste version så eller den seneste?

**Comment by scaarup** [comment]
> > Ja det er god info @Uberpainer og @jascdk - tak.
> > Kan I også bekræfte, at det hele virkede fint før seneste version?
> 
> Alt virkede før ja - jeg har lige prøvet at installere din nye branch - syntes ikke det ændrer sig - skal jeg bruge sidst nyeste version så eller den seneste?

Jeg har lige lavet en prerelease/beta, der hedder v.0.1.20. Vil du prøve at opdatere til den i HACS?

**Comment by jascdk** [comment]
> > > Ja det er god info @Uberpainer og @jascdk - tak.
> > > Kan I også bekræfte, at det hele virkede fint før seneste version?
> > 
> > 
> > Alt virkede før ja - jeg har lige prøvet at installere din nye branch - syntes ikke det ændrer sig - skal jeg bruge sidst nyeste version så eller den seneste?
> 
> Jeg har lige lavet en prerelease/beta, der hedder v.0.1.20. Vil du prøve at opdatere til den i HACS?

Ahhh - got it - den er installeret og det lader til at være som før nu - så det virker ;) Stærkt!

**Comment by scaarup** [comment]
Fedt - det var godt at høre 🙂
