### ISSUE TITLE
Fejl i forbindelse med opsætning

### ISSUE THREAD

**Issue by Ronnie-J** [scaarup/aula#53]
**Describe the bug or problem (In Danish is OK)**
Jeg udfylder integrationen med log-in detaljer, og udelader flueben i noget andet (samme resultat med flueben). Min søn går i 0. klasse, datter i vuggestue.

**Please answer the following**
- Version of integration: Aula integration, version: 0.1.25
- Version of Home Assistant: Home Assistant 2022.12.1
- [Ja, men ikke i skole] I have more than one child
- [Ja] My children are attending different schools / institutions

**Please provide debug log from the integration**
```
2022-12-09 13:15:35.584 ERROR (MainThread) [custom_components.aula.sensor] Unexpected error fetching sensor data: 'action'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 181, in _async_update_data
return await self.update_method()
File "/config/custom_components/aula/sensor.py", line 43, in async_update_data
await hass.async_add_executor_job(client.update_data)
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/aula/client.py", line 85, in update_data
self.login()
File "/config/custom_components/aula/client.py", line 38, in login
url = html.form['action']
File "/usr/local/lib/python3.10/site-packages/bs4/element.py", line 1519, in __getitem__
return self.attrs[key]
KeyError: 'action'
2022-12-09 13:15:35.588 DEBUG (MainThread) [custom_components.aula.sensor] Finished fetching sensor data in 1.059 seconds (success: False)
2022-12-09 13:15:35.591 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up aula platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/aula/sensor.py", line 58, in async_setup_entry
await hass.async_add_executor_job(client.update_data)
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/aula/client.py", line 79, in update_data
response = self._session.get(self.apiurl + "?method=profiles.getProfilesByLogin", verify=True).json()
AttributeError: 'Client' object has no attribute 'apiurl'
```

**Comment by scaarup** [comment]
Jeg kan ikke lige genskabe dit problem:
Du ser ikke engang loglinjer som disse?
````
2022-12-09 13:31:20.591 INFO (MainThread) [homeassistant.setup] Setting up aula
2022-12-09 13:31:20.592 INFO (MainThread) [homeassistant.setup] Setup of domain aula took 0.0 seconds
2022-12-09 13:31:20.596 INFO (MainThread) [custom_components.aula]
                _
     /\        | |
    /  \  _   _| | __ _
   / /\ \| | | | |/ _` |
  / ____ \ |_| | | (_| |
 /_/    \_\__,_|_|\__,_|
Aula integration, version: 0.1.25
This is a custom integration
If you have any issues with this you need to open an issue here:
https://github.com/scaarup/aula/issues
-------------------------------------------------------------------

2022-12-09 13:31:20.611 INFO (MainThread) [homeassistant.components.sensor] Setting up sensor.aula
2022-12-09 13:31:20.615 DEBUG (SyncWorker_11) [custom_components.aula.client] is_logged_in? False
2022-12-09 13:31:20.616 DEBUG (SyncWorker_11) [custom_components.aula.client] Logging in
2022-12-09 13:31:22.466 DEBUG (SyncWorker_11) [custom_components.aula.client] Trying API at https://www.aula.dk/api/v15
2022-12-09 13:31:22.683 DEBUG (SyncWorker_11) [custom_components.aula.client] Found API on https://www.aula.dk/api/v15
````

**Comment by Ronnie-J** [comment]
@scaarup jov beklager - netop udvidet i den originale post. Jeg har ikke linjerne som dig efter `Logging in`. 
Jeg har netop testet med at installere integrationen på ny, samme problem. Testet log-in på aula.dk hvor jeg fint kommer ind.

**Comment by scaarup** [comment]
Kan vi lige prøve at lille manuelt hack - prøv at skriv dit brugernavn og password direkte ind i client.py på linjerne 22 og 23:
![image](https://user-images.githubusercontent.com/8055470/206706274-4c73e526-2548-4729-a0d3-3564b1810290.png)

**Comment by Ronnie-J** [comment]
@scaarup tak for den hurtige feedback. Jeg har redigeret `client.py` som anvist, men med samme resultat. 
Jeg koder ikke i Python, men hvis jeg selv skal fortolke så ser det ud til at den ikke er kommet tilbage med den forventede HTML for at gennemfører log-in. 

Smækkede en debug linje ind på linje `37`, og kan se den kommer forbi to gange i alt.

```
        while success == False and redirects < 10:
            _LOGGER.debug("Redirect "+ str(redirects))
```

```
2022-12-09 20:22:57.250 DEBUG (SyncWorker_1) [custom_components.aula.client] Logging in
2022-12-09 20:22:58.086 DEBUG (SyncWorker_1) [custom_components.aula.client] Redirect 0
2022-12-09 20:22:58.389 DEBUG (SyncWorker_1) [custom_components.aula.client] Redirect 1
2022-12-09 20:22:58.396 ERROR (MainThread) [custom_components.aula.sensor] Unexpected error fetching sensor data: 'action'
```

**Comment by Ronnie-J** [comment]
Kan det have noget at gøre med at efter min søns brugernavn bliver indtastet så redirectes man videre til Egedal's egen IDP? 
![Screenshot (3)](https://user-images.githubusercontent.com/7793111/206782022-fa95abac-81c8-44f8-9696-caf4b476157d.jpg)

**Comment by scaarup** [comment]
Har du indtastet din søns brugernavn? Det skal være dit eget.

**Comment by Ronnie-J** [comment]
@scaarup interessant 😄 jeg har kun adgang til Aula via MitID, og jeg har for nyligt modtaget min søns Uni-login. Uni-login er da kun til elever?

**Comment by scaarup** [comment]
Nej unilogin er både til elever og forældre 🙂

**Comment by Ronnie-J** [comment]
Deri lå hele problemet! Beklager forvirringen 😆

**Comment by scaarup** [comment]
👍🙂
