### ISSUE TITLE
Jeg får ingen entiteter indlæst

### ISSUE THREAD

**Issue by martikejs2020** [scaarup/aula#74]
Hej Scaarup.

Jeg er i tvivl om det er mig selv der er fejlen i det her.
Jeg har hentet Aula-integrationen gennem Hacs, og bliver i konfigurationen mødt med Unilogin brugernavn og adgangskode.
I de to bokse har jeg forsøgt kun at vinge skoleskemaet af, men tidligere også med begge og ingen.
Jeg kan dog ikke spotte en entitet fra Aula.
under config/custom-components/aula ligger der de filer der skal.

Aula: v 0.1.28 (Jeg fik heller ikke v.0.1.27 til at virke)
Hacs: v 1.29.1

Jeg har manuelt i configuration.yaml tilføjet

aula:
  unilogin_username: **********
  unilogin_password: *********
(Det mener jeg at have læst et sted, at der skulle tilføjes ?

Er der noget python noget der skal køres, før at integrationen virker ?

Jeg har tre børn, men har kun forsøgt at logge ind med Unilogin for det ene barn.

Min debug-log er følgende:

2023-01-24 11:22:53.502 ERROR (MainThread) [custom_components.aula.sensor] Error requesting sensor data: Invalid URL '/adfs/ls/?SAMLRequest=nVNNT%2BMwEP0rke%2BJE6cIsJpKhWq1lWA3ot097AU58QS8dezgcbrLv8dNjWAv1cLJH%2FNm3sx79hxFrwe%2BHP2juYOnEdAnf3ttkE%2BBiozOcCtQITeiB%2BS%2B5Zvl7Q1nWc4HZ71trSbHlNNggQjOK2tIsnzdXluDYw9uA26vWvhxd1ORR%2B8H5JQ2zu7AZaNR2j4ok8kdFaFL6kDoHmP4dXHCSHBIwcjBKuNJsgqTKCMOLG81hewwcztUfioXTlQjJckX61qYNKhIJzQCSdariqxX90VelCUDlsqyuUhnl7JNG3bZpl3XnUvomvOGFQGMdRhP7eEtHXGEtUEvjK8Iy1mZ5kXKZtsi54zxszJj7OIXSeoo4ZUyUpmH0xI2RxDyr9ttndbfN1uS%2FAxjTzMGAFnMD67xidy98%2FF%2FnVl8SPw5fccWqTdj8xta%2FxnuY4FvAbJeLfZCyzI%2Fm0WOeBtPkeSYMcRgbbVqn5Ol1vbPdejTBzO8G2Fytxf%2BdB%2BHGyXTboLy4SAqeggPiUbSf%2F%2FI4gU%3D&RelayState=Xz0wAvfqs_2jpPCcranU-KPWJY4_H87VuW85e0Wit4Q.hyO5sLn_4PY.https%3A%2F%2Fprod-uni.aula.dk%2Fsimplesaml%2Fsaml2%2Fidp%2Fmetadata.php&SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmldsig-more%23rsa-sha256&Signature=CYYjhXfpVsk8XYbzQpsWzfYamFz%2FOPRC5g4cM8p6qDMRFyU%2Fo4itj%2B2x3Jia39BTBhod7RtMQYFx7YfXGcqQvkFMMXGPByAaHg%2B9MefnwCbOCNOUjmORZ01fTNixpf8Gq0kzNhPCLfqcT7UiUL0o5auhU1XhxcjlFOIeBIZZW15d7nozrm6r%2Frg1JwBBLcCGheLBRiIWtU29i8D2hpQlrl1nAkehbOXUN3BL0jseGt4p9rvtOZB7V6fQxhmqFxKE5XVrhSrN3qN0I7dtY%2BNSW%2BPb3AeKJLXBpKJf%2B%2BgNUYcRX7QHXZb2ToXksy3gebX1E5eyS%2FpJFFqwJLsQF8QJKw%3D%3D&client-request-id=43d4cc48-49b7-435e-4396-008000000073': No scheme supplied. Perhaps you meant http:///adfs/ls/?SAMLRequest=nVNNT%2BMwEP0rke%2BJE6cIsJpKhWq1lWA3ot097AU58QS8dezgcbrLv8dNjWAv1cLJH%2FNm3sx79hxFrwe%2BHP2juYOnEdAnf3ttkE%2BBiozOcCtQITeiB%2BS%2B5Zvl7Q1nWc4HZ71trSbHlNNggQjOK2tIsnzdXluDYw9uA26vWvhxd1ORR%2B8H5JQ2zu7AZaNR2j4ok8kdFaFL6kDoHmP4dXHCSHBIwcjBKuNJsgqTKCMOLG81hewwcztUfioXTlQjJckX61qYNKhIJzQCSdariqxX90VelCUDlsqyuUhnl7JNG3bZpl3XnUvomvOGFQGMdRhP7eEtHXGEtUEvjK8Iy1mZ5kXKZtsi54zxszJj7OIXSeoo4ZUyUpmH0xI2RxDyr9ttndbfN1uS%2FAxjTzMGAFnMD67xidy98%2FF%2FnVl8SPw5fccWqTdj8xta%2FxnuY4FvAbJeLfZCyzI%2Fm0WOeBtPkeSYMcRgbbVqn5Ol1vbPdejTBzO8G2Fytxf%2BdB%2BHGyXTboLy4SAqeggPiUbSf%2F%2FI4gU%3D&RelayState=Xz0wAvfqs_2jpPCcranU-KPWJY4_H87VuW85e0Wit4Q.hyO5sLn_4PY.https%3A%2F%2Fprod-uni.aula.dk%2Fsimplesaml%2Fsaml2%2Fidp%2Fmetadata.php&SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmldsig-more%23rsa-sha256&Signature=CYYjhXfpVsk8XYbzQpsWzfYamFz%2FOPRC5g4cM8p6qDMRFyU%2Fo4itj%2B2x3Jia39BTBhod7RtMQYFx7YfXGcqQvkFMMXGPByAaHg%2B9MefnwCbOCNOUjmORZ01fTNixpf8Gq0kzNhPCLfqcT7UiUL0o5auhU1XhxcjlFOIeBIZZW15d7nozrm6r%2Frg1JwBBLcCGheLBRiIWtU29i8D2hpQlrl1nAkehbOXUN3BL0jseGt4p9rvtOZB7V6fQxhmqFxKE5XVrhSrN3qN0I7dtY%2BNSW%2BPb3AeKJLXBpKJf%2B%2BgNUYcRX7QHXZb2ToXksy3gebX1E5eyS%2FpJFFqwJLsQF8QJKw%3D%3D&client-request-id=43d4cc48-49b7-435e-4396-008000000073?
2023-01-24 11:22:53.506 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up aula platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/aula/sensor.py", line 58, in async_setup_entry
await hass.async_add_executor_job(client.update_data)
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/aula/client.py", line 103, in update_data
response = self._session.get(self.apiurl + "?method=profiles.getProfilesByLogin", verify=True).json()
AttributeError: 'Client' object has no attribute 'apiurl'
2023-01-24 11:23:09.345 ERROR (MainThread) [custom_components.aula.sensor] Unexpected error fetching sensor data: 'NoneType' object is not subscriptable
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 181, in _async_update_data
return await self.update_method()
File "/config/custom_components/aula/sensor.py", line 43, in async_update_data
await hass.async_add_executor_job(client.update_data)
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/aula/client.py", line 109, in update_data
self.login()
File "/config/custom_components/aula/client.py", line 79, in login
self._profilecontext = self._session.get(self.apiurl + "?method=profiles.getProfileContext&portalrole=guardian", verify=True).json()['data']['institutionProfile']['relations']
TypeError: 'NoneType' object is not subscriptable
2023-01-24 11:23:10.674 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up aula platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/aula/sensor.py", line 58, in async_setup_entry
await hass.async_add_executor_job(client.update_data)
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/aula/client.py", line 154, in update_data
for message in threadres.json()["data"]["messages"]:
TypeError: 'NoneType' object is not subscriptable

**Comment by scaarup** [comment]
Hej @martikejs2020 

Det er vigtigt, at du bruger dit eget unilogin - ikke dine børns.
Derudover skal du ikke konfigurere brugernavn og password i din configuration.yaml - det skal kun ske i UI opsætningen af aula.
Sidst - du serverer ikke debug log. Det er udelukkende ERROR log-linjer. Men det betyder måske heller ikke meget hvis du får logget ind som dig selv og forhåbentlig løst problemet.

**Comment by martikejs2020** [comment]
Jeg var slet ikke klar over at jeg havde et unilogin.
Jeg trode kun at vi kunne logge ind med NemID/MitID.
Jeg har nu konfigureret Aula-integrationen med nyt brugernavn og password.
Det virker (Y) tak.

Vi har tre børn herhjemme, hvoraf to af dem har en anden far.
Jeg plejer godt at kunne se deres skoleskemaer m.v. på Aula.
Men jeg får kun 3 entities ind i aula for den ene af de tre.

binary_sensor.aula_aulamessage
sensor.institution_barn1
calendar.skoleskema_barn1

**Comment by scaarup** [comment]
Okay, det var da et fremskridt :)

Så bliver vi nødt til at have fat i debug loggen, hvis vi skal se hvad der foregår.

**Comment by martikejs2020** [comment]
Jeg prøvede med fruens unilogin.
Så får jeg data fra alle tre.
Så det er tilsyneladende noget administration hvad jeg kan tilgå

Jeg er spændt på hvad i finder ud af med "min ugeplan". 
Jeg følger tråden tæt.
