### ISSUE TITLE
Efter seneste upgrade af aula plugin får jeg ingen data ind i systemet

### ISSUE THREAD

**Issue by tocDK** [scaarup/aula#75]
**Describe the bug or problem (In Danish is OK)**
Efter seneste upgrade af aula plugin får jeg ingen data ind i systemet. Jeg har vedhæftet de 2 fejl jeg får i loggen

**Please answer the following**
- Version of integration: v0.1.27
- Version of Home Assistant:  Home Assistant 2023.1.7
- [ x ] I have more than one child
- [ x ] My children are attending different schools / institutions

**Please provide debug log from the integration**
- Enable by adding the following to your configuration.yaml:
```
logger:
  default: info
  logs:
    custom_components.aula: debug
```
- Restart Home Assistant
- Capture all log lines (from the integration only), save it to a file and attach it to here.

```
Logger: homeassistant.components.sensor
Source: custom_components/aula/client.py:155
Integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 10:19:52 (1 occurrences)
Last logged: 10:19:52

Error while setting up aula platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/aula/sensor.py", line 58, in async_setup_entry
    await hass.async_add_executor_job(client.update_data)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/aula/client.py", line 155, in update_data
    self.message["text"] = message["text"]["html"]
TypeError: 'NoneType' object is not subscriptable
```

```
Logger: custom_components.aula.sensor
Source: custom_components/aula/client.py:155
Integration: Aula ([documentation](https://github.com/scaarup/aula/blob/main/README.md), [issues](https://github.com/scaarup/aula/issues))
First occurred: 10:19:50 (1 occurrences)
Last logged: 10:19:50

Unexpected error fetching sensor data: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 181, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/aula/sensor.py", line 43, in async_update_data
    await hass.async_add_executor_job(client.update_data)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/aula/client.py", line 155, in update_data
    self.message["text"] = message["text"]["html"]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by scaarup** [comment]
Hej Thomas.
Tak for din bugreport. Jeg blev så småt opmærksom på fejlen i går.

Har du mod på at teste om denne branch løser problemet: https://github.com/scaarup/aula/tree/hot-fix-messages ?

**Comment by tocDK** [comment]
@scaarup Ja. Jeg er semi ny i HA. Skal den installeres som en manuel installation?

**Comment by scaarup** [comment]
Du kan egentlig bare finde client.py (normalt i /config/custom_components/aula/client.py) og copy/paste det hele herfra: https://github.com/scaarup/aula/blob/hot-fix-messages/custom_components/aula/client.py 
og så genstarte HA.

**Comment by scaarup** [comment]
Hvis det er noget rod, så kan jeg lave en beta/prelease, der kan installeres via HACS.

**Comment by tocDK** [comment]
@scaarup nej, jeg finder ud af det. giv mig lige 10 min

**Comment by tocDK** [comment]
@scaarup det virker

**Comment by scaarup** [comment]
Fedt - mange tak for at teste.
Jeg releaser den med det samme.
